### ISSUE TITLE
Current contact email addresses across pypi / github documentation are incorrect.

### ISSUE THREAD

**Issue by butler54** [IBM/compliance-trestle#1001]
## Describe the bug
Contact email address in setup.cfg and other parts of the docs point to `chris.butler@au1.ibm.com`. It may make sense to create non-user ID to be the first point of contact and replace in various places. This applies to:
https://github.com/IBM/compliance-trestle
and 
https://github.com/IBM/compliance-trestle-fedramp

**Comment by vikas-agarwal76** [comment]
done
