### ISSUE TITLE
Profile does not have parameters in yaml header

### ISSUE THREAD

**Issue by deenine** [IBM/compliance-trestle#1002]
## Describe the bug

Profiles only store the parameters in the verbiage, which is not obvious to modify and presumably cannot be imported back into the profile when `profile-assemble` is run.

It would be useful to store parameters in yaml per the catalog update, and leave the [xx-n_prm_n] in the verbiage to show where the parameter goes, and have ability to set the parameters in the json from the md profile. 
```
---
x-trestle-set-params:
  ac-1_prm_1: organization-defined personnel or roles
  ac-1_prm_2: organization-defined frequency
  ac-1_prm_3: organization-defined frequency
---
```
## To Reproduce

1. Click on '....'
1. Scroll down to '....'
1. See error

## Environment

- OS: \[e.g. iOS\]
- Python version:
- Installed packages:

**Comment by fsuits** [comment]
This is already implemented by specifying --set-parameters during profile-generate:

```---
x-trestle-set-params:
  ac-1_prm_1: all personell
  ac-1_prm_2: A thorough
  ac-1_prm_3: officer
  ac-1_prm_4: weekly
  ac-1_prm_5: all meetings
  ac-1_prm_6: monthly
  ac-1_prm_7: conferences
---

# ac-1 - \[Access Control\] Policy and Procedures
```

The markdown for the control will have the header at the top, and the text in the markdown will have those substitutions made.

You can then edit those values and again use --set-parameters when doing profile-assemble and the profile will incorporate those changes.

It may be that we should remove the --set-parameters option so this always happens on generate and assemble, but some use cases may prefer not to have the header in the markdown.  Currently it is on and cannot be turned off in catalog-generate and catalog-assemble, but it is an option in profile-generate and profile-assemble.

There is a related option --preserve-header-values that gives priority to the values in the markdown header and prevents overwrite by values in a provided yaml header.  It may be that this should be the default and instead we provide an option, --overwrite-header-values when we do want the provided yaml header to have priority.  In all cases, any values in the provided yaml header that are not already present in the markdown header will be added.

--preserve-header-values is an option for all cases where a yaml header may be provided: catalog-generate, profile-generate and ssp-generate

There is brief documentation on these flags in the docs but it should be expanded once we decide on the above.

**Comment by deenine** [comment]
Thanks, Ive tested this and now have yaml headers with the parameters. I agree that the values in the markdown header should have priority by default.

I think it is worth updating the output formatting of the profile to make it clear where the parameter sits in the control text, for example :

> [b] Reviews and updates the current:
> 
>     [1] Contingency planning policy at least annually; and
>.    [2] Contingency planning procedures at least annually.

Its not instantly obvious which parameter sits where, so suggest something like:

> [b] Reviews and updates the current:
> 
>     [1] Contingency planning policy [cp-1_prm_2]
>.    [2] Contingency planning procedures [cp-1_prm_3].
