### ISSUE TITLE
Remove duplicate error/warning messages

### ISSUE THREAD

**Issue by fsuits** [IBM/compliance-trestle#1009]
## Issue description / feature objectives
Some errors trigger redundant messages, e.g.:

```
trestle.core.base_model:327 ERROR: Failed to parse OSCAL object: OSCAL version: 1.0.1 is not supported, use 1.0.0 instead.
trestle.core.commands.validate:52 ERROR: Error while validating contents of a trestle model: Error parsing file C:\tmp\test\profiles\fedramp\profile.json OSCAL version: 1.0.1 is not supported, use 1.0.0 instead.
```

This is due to an inner exception being caught and outputting a message, then later an outer exception is caught and this is repeated:

inner:
```python
        except Exception as e:
            logger.error(f'Failed to parse OSCAL object: {e}')
            raise err.TrestleError(f'Error parsing file {path} {str(e)}')
```
outer:
```python
        except TrestleError as e:
            logger.debug(traceback.format_exc())
            logger.error(f'Error while validating contents of a trestle model: {e}')
            return CmdReturnCodes.COMMAND_ERROR.value
```

## Caveats / Assumptions
The redundant info is distracting
## Completion Criteria
Decide how to handle this situation consistently
Also - should this be a warning?  It is due to bad data from the user and not a problem in trestle code.

**Comment by enikonovad** [comment]
I believe the proper way to handle it would be 
1) To switch all the `inner` logger error messages to the `debug level` and print only the `outer` error.  
2) As for `warnings`, I believe some of them do not halt the execution, thus printing them is fine. However, if there are some "warnings" that do in fact end the execution and raise an exception, they should be treated as errors and moved to the `debug` level as well.
