### ISSUE TITLE
Provide tests to cover existing chunks of missed functionality

### ISSUE THREAD

**Issue by fsuits** [IBM/compliance-trestle#1021]
## Issue description / feature objectives
There are a few files with large-ish chunks of code that don't have coverage.  Some can easily have tests created and overall coverage would boost.
## Caveats / Assumptions
Focus on the large and easier ones.

**Comment by vikas-agarwal76** [comment]
More test cases needed for document authoring.

**Comment by vikas-agarwal76** [comment]
Done. We are at 97.6% code coverage.
