### ISSUE TITLE
Do not create md files for withdrawn controls

### ISSUE THREAD

**Issue by deenine** [IBM/compliance-trestle#1041]
## Describe the bug

`trestle author catalog-generate -n NIST_800-53_rev4 -o md_catalogs/NIST_800-53_rev4/` results in creation of empty markdown files, where NIST has marked the control 'withdrawn', for example[ AU-2.2](https://csrc.nist.gov/Projects/risk-management/sp800-53-controls/release-search#!/control?version=4.0&number=AU-2) results in:

```
# au-2.2 - \[Audit and Accountability\] Selection of Audit Events by Component

## Control Statement
```

## To Reproduce

1. Download nist 800-53 rev4 from https://github.com/usnistgov/oscal-content
1. Install trestle with make develop2. 
1. create a directory and run trestle init.
1. paste the nist 800-53 rev4 json file into catalogs/NIST_800-53_rev4
1. trestle author catalog-generate -n NIST_800-53_rev4 -o md_catalogs/NIST_800-53_rev4/
1. `cat md_catalogs/NIST_800-53_rev4/au/au-2.2.md `

## Expected behavior

Do not create markdown files for withdrawn controls.

**Comment by fsuits** [comment]
@deenine 
https://github.com/IBM/compliance-trestle/pull/1045

New PR will block withdrawn controls from being written to markdown.
