### ISSUE TITLE
Review trestle -h output for all commands and update as needed

### ISSUE THREAD

**Issue by fsuits** [IBM/compliance-trestle#1044]
## Describe the bug
Many of the trestle -h docstrings are out of date.

trestle author refers to "outside of OSCAL" and that is not true anymore.
the text for create needs updating for the new add capability
Ensure all command descriptions are up to date.

## To Reproduce

1. Click on '....'
1. Scroll down to '....'
1. See error

## Environment

- OS: \[e.g. iOS\]
- Python version:
- Installed packages:

**Comment by vikas-agarwal76** [comment]
done
