### ISSUE TITLE
Check existing FIXMEs and TODOs in the project

### ISSUE THREAD

**Issue by enikonovad** [IBM/compliance-trestle#1059]
## Issue description / feature objectives
The project has a lot of `FIXME` and `TODO` statements that are now lost in time. This issue is to go over all the existing `FIXME` and `TODO` in the project and check whether they are still relevant or should be fixed.

If the fix is complicated, a new issue should be created and `FIXME` should be changed to `FIXME-<number_of_the_issue>`

## Completion Criteria
All `FIXME` are either fixed or an issue was created and comment changed to `FIXME-<number_of_the_issue>`
All `TODO` are either completed or an issue was created and comment changed to `TODO-<number_of_the_issue>`

**Comment by vikas-agarwal76** [comment]
Mostly done. Still left in couple of places. Not major.
