### ISSUE TITLE
Handle OSCAL 1.0.2 patch changes in current code or separate branch

### ISSUE THREAD

**Issue by fsuits** [IBM/compliance-trestle#1063]
## Describe the bug
We have previously been working with OSCAL 1.0.0 but there have now been two patches and the current version available is 1.0.2.

[OSCAL 1.0.2 patch](https://pages.nist.gov/OSCAL/reference/release-notes/#oscal-102-release)

This patch has a few changes that require special handling:

1. A breaking change was made in AssessmentPlan where a typo had named an attribute 'prop' instead of 'props'.  Fixing this typo by renaming `prop` to `props` in the class broke many of the osco/tanium task tests that rely on AssessmentPlan.  It was easy to change the code and fix all the tests, but we need to decide either to move all to 1.0.2 or support two branches.
2. Our tests rely on a simplified version of the NIST catalog that is generated by the make routine `make simplfied-catalog`.  When this is run with the new version of the catalog it breaks many tests because the names of parameters has greatly changed in the new version.  I don't think there is any change in the schema and we can continue to use the previous version of the simplified catalog, but there is now a barrier that makes it hard to regenerate the catalog.

Aside from these issues there was a minor change to `generators.py` but it is backward compatible with OSCAL 1.0.0 and shouldn't be an issue.

## Action
Decide whether to support only 1.0.2 or start a separate branch.

**Comment by enikonovad** [comment]
My thoughts on this issue. 

I believe we should be using the latest version of the OSCAL 1.0.2 (and only that version) for two major reasons:
1) Supporting two separate branches is not realistic in the long-term. As we move forward, new features will be added and having two separate branches would mean doing same task twice for each version.

2) Minor versions usually fix some issues/bugs and it is in our best interest to use the version with less bugs.

Therefore, my view would be that if the changes are minor, we should switch to the latest version and only support that one.

**Comment by vikas-agarwal76** [comment]
trestle 1.0.0 will release with OSCAL 1.0.0. For latest OSCAL schema, we will update trestle after the release.

**Comment by vikas-agarwal76** [comment]
done.
