### ISSUE TITLE
Trestle stable release 1.0

### ISSUE THREAD

**Issue by enikonovad** [IBM/compliance-trestle#1066]
## Issue description / feature objectives
Before releasing Trestle 1.0, there are several steps that needs to be done and some files that needs to be updated to reflect the `stable` release.

1. Create a release branch 1.0 with the release candidate
2. Change development status to `stable` for pypi
3. Update README.md to reflect that Trestle is now in `stable` version.
4. Double check that docs reflect correct version of OSCAL (1.0.0)
5. Create a commit with breaking change to trigger semantic-versioning to release a major version of 1.0
6. Anything else?

[Useful link](https://py-pkgs.org/07-releasing-versioning.html)
Once everything is ready, we can proceed with releasing 1.0

**Comment by vikas-agarwal76** [comment]
Done.
