### ISSUE TITLE
Excel to OSCAL workflows for incremental change while maintaining consistent UUIDS

### ISSUE THREAD

**Issue by butler54** [IBM/compliance-trestle#107]
## Issue description / feature objectives
An unfortunate reality of OSCAL is that many conversions to OSCAL will not be once off. Some teams will want to maintain workflows where they edit in excel (our exemplar here) or similar as a primary source as opposed to OSCAL (ideally) being the primary document.

If we look at `control-implementation` within the `component-definition` the issue here is UUIDs are the tracking technique - there are no other fields that are guaranteed to be unique. UUIDs would (typically) be generated by trestle. 

This is okay for a once off - the issue becomes on update management.

Given this:
1) UUIDs get written back to the source (excel or similar) document to be used for tracking. This would allow resolution of UUIDs to appropriate rows.
2) For this to work an excel parsing utility would explicitly need to be part of trestle. As opposed to the current model where excel parsing is the users responsibility using trestle as a library.
3) This could be helped by having a 'standardized' OSCAL -> excel and excel -> OSCAL for a subset of key artifacts.[

The Alternative
1) OSCAL is the primary document and that is it. Use trestle to manage complexity by breaking down documents.

## Completion Criteria
- [ ] Approach decided and documented with appropriate github issues for individual tasks.

**Comment by EyshaShirrine** [comment]
Thanks @butler54!

**Comment by butler54** [comment]
Closing with current workflows that exist so far.
