### ISSUE TITLE
Converting catalog to markdown and back to json looses catalog title

### ISSUE THREAD

**Issue by deenine** [IBM/compliance-trestle#1073]
## Describe the bug

Taking a json catalog (such as the [800-53r4 reference catalog](https://github.com/usnistgov/oscal-content/blob/main/nist.gov/SP800-53/rev4/json/NIST_SP-800-53_rev4_catalog.json)) and converting to markdown, and then back to json causes the catalog title to be replaced with 'REPLACE_ME':

## To Reproduce

1. mkdir trestletest
1. cd trestletest/
1. . ../../compliance-trestle/venv.trestle-develop/bin/activate
1. trestle init
1.  trestle import -f ../oscal-content/nist.gov/SP800-53/rev4/json/NIST_SP-800-53_rev4_catalog.json -o NIST_SP-800-53_rev4
1. trestle author catalog-generate --name NIST_SP-800-53_rev4 --output md_catalogs/NIST_800-53_rev4
1. trestle author catalog-assemble -v --set-parameters --markdown md_catalogs/NIST_800-53_rev4 --output NIST_SP-800-53_rev4
1. head catalogs/NIST_SP-800-53_rev4/catalog.json 

```
head catalogs/NIST_SP-800-53_rev4/catalog.json 
{
  "catalog": {
    "uuid": "fd2eac2a-1ec9-4f66-990e-9dcecab12055",
    "metadata": {
      "title": "REPLACE_ME",
      "last-modified": "2022-03-29T15:22:35.697670+01:00",
      "version": "REPLACE_ME",
      "oscal-version": "1.0.0"
    },
    "controls": [],
```

## Expected behavior

```
head ../oscal-content/nist.gov/SP800-53/rev4/json/NIST_SP-800-53_rev4_catalog.json 
{
  "catalog": {
    "uuid": "b954d3b7-d2c7-453b-8eb2-459e8d3b8462",
    "metadata": {
      "title": "NIST Special Publication 800-53 Revision 4: Security and Privacy Controls for Federal Information Systems and Organizations",
      "last-modified": "2021-06-08T13:57:28.91745-04:00",
      "version": "2015-01-22",
      "oscal-version": "1.0.0",
      "props": [
        {
```

**Comment by deenine** [comment]
This could probably be solved by `trestle import` should write catalog metadata that does not fit into the per control MD into the .trestle directory.

Probably we should not be round tripping for upstream catalogs, but this seems like a requirement that also applies to managing custom catalogs

**Comment by fsuits** [comment]
This is as intended and the solution is always to provide the original "parent" catalog during assembly.  The assembly process always takes the parent catalog, and its metadata, and pulls in the new content from the markdown to make the new catalog - and then it should check if the result is new relative to the destination json catalog - and not write it out if there is nothing new.

This is the only way metadata and backmatter can be captured and retained.  The destination catalog may not be present yet, when first assembled - and after that the destination catalog is only checked for the purpose of detecting changes that need to be written out.  I will clarify this in the docs.

So assembly requires 1) the parent json catalog, 2) the source markdown catalog and 3) the destination json catalog.  So just provide the optional --name of the original json catalog:

```
usage: trestle author catalog-assemble [-h] [--name NAME] -m MARKDOWN -o OUTPUT [-sp] [--regenerate] [--version VERSION] [-v] [-tr TRESTLE_ROOT]

Assemble markdown files of controls into a Catalog json file.

optional arguments:
  -h, --help            show this help message and exit
  --name NAME, -n NAME  Optional name of the catalog model in the trestle workspace that is being modified. If not provided the output name is used.
  -m MARKDOWN, --markdown MARKDOWN
                        Name of the input markdown file directory
  -o OUTPUT, --output OUTPUT
                        Name of the output generated json Catalog
  -sp, --set-parameters
                        set profile parameters and values based on the yaml header in control markdown
  --regenerate, -r      Flag to force generation of new uuids in the model
  --version VERSION, -vn VERSION
                        New version for the assembled model
```

**Comment by fsuits** [comment]
This is working as intended but I should probably change it.  During assemble  the --name refers to a parent catalog that is used as the source of metadata.  If you don't specify it then the new json file is created straight from the markdown and there is no metadata including title.  This allows a user to create the catalog either anew, from the markdown only, or to specify the parent explicitly.

But I could allow the default behavior, if no --name is specified, to load from the existing assembled json file if it already exists.  That is probably better - but it means if you want to create the catalog just from the markdown you will need to erase the previously assembled catalog, or direct the output to a new catalog name.

So I will change that default behavior.
