### ISSUE TITLE
trestle -h gives warning that "blowfish has been deprecated"

### ISSUE THREAD

**Issue by fsuits** [IBM/compliance-trestle#1111]
## Describe the bug
trestle -h current gives a warning: `(trestle) C:\fs\src\compliance-trestle>trestle -h
C:\fs\envs\trestle\lib\site-packages\paramiko\transport.py:236: CryptographyDeprecationWarning: Blowfish has been deprecated
  "class": algorithms.Blowfish,`

This is due to a change in a dependence related to paramiko: https://github.com/paramiko/paramiko/issues/2038

That link indicates there will be a future release of paramiko that will quiet the message.  Since the only impact to trestle is a warning message I suggest monitoring and making sure a future version of paramiko does resolve the issue.

**Comment by ARMoir** [comment]
Commenting out the `blowfish-cbc` entire in the `_cipher_info` JSON starting on line 236 of `paramiko\transport.py` has resolved the issue for me.

        #"blowfish-cbc": {
        #    "class": algorithms.Blowfish,
        #    "mode": modes.CBC,
        #    "block-size": 8,
        #    "key-size": 16,
        #},

**Comment by fsuits** [comment]
Thanks @ARMoir - it's good people can fix things in their local installation.  I will look into automatically installing an earlier version of dependencies if possible, as an interim solution so people won't need to do anything special.

**Comment by fsuits** [comment]
I created PR to force load of earlier cryptography release and it should fix the problem.
