### ISSUE TITLE
Move from OSCAL 1.0.2 to 1.0.4 to handle rare regex date issues

### ISSUE THREAD

**Issue by fsuits** [IBM/compliance-trestle#1131]
## Issue description / feature objectives
OSCAL 1.0.4 is out and it fixes regex issues that are either old, or they were introduced in 1.0.3.  They could cause a validation error with certain date/time formats, so moving forward is advisable.
## Completion Criteria
Support OSCAL 1.0.4 and rebuild oscal classes

**Comment by vikas-agarwal76** [comment]
We will directly move to OSCAL 1.1
