### ISSUE TITLE
"Last modified" is updated during the catalog-assemble even if there are no changes

### ISSUE THREAD

**Issue by enikonovad** [IBM/compliance-trestle#1136]
## Describe the bug

When running 
> trestle author catalog-assemble -v --set-parameters --markdown md_catalogs/NIST_800-53_rev4 --output NIST_800-53_rev4

with **no** changes, the `last-modified` field in the OSCAL json will be updated to the current date.

## To Reproduce

1. Have a collection of markdown catalogs that were previously assembled (i.e. `md_catalogs/NIST_800-53_rev4`)
2. Don't do any changes
3. Run  trestle author catalog-assemble -v --set-parameters --markdown md_catalogs/NIST_800-53_rev4 --output NIST_800-53_rev4`
4. Observe that `last_modified` inside `NIST_800-53_rev4/catalog.json` was updated to the current date.

## Expected behavior

`last_modified` should not be updated unless there are actual changes.

## Environment
- compliance-trestle 1.1.0 and
- latest develop

**Comment by fsuits** [comment]
This was subtle and caused by an empty params list being added to the assembled catalog on the *second* assemble, where a catalog was already present.  If you were to assemble again, it would not have overwritten.  Making sure an empty params list is never output solves the problem.
