### ISSUE TITLE
trestle csv to oscal component-definition task

### ISSUE THREAD

**Issue by degenaro** [IBM/compliance-trestle#1141]
## Issue description / feature objectives

Produce one or component-definitions in a trestle workspace from.
Arguments:
--csv-file \<path of CSV file, absolute or relative to the trestle workspace> (required)
~~--profile \<name of the profile in the trestle workspace> (required)~~
--components “comp1:comp2” filter on CSV file to create only specified components (optional)
~~--rules-version \<say 1.1> (optional)~~
--namespace “http://ibm.github.io/compliance-trestle/schemas/oscal/cd/ibm-cloud” (optional)
~~--property-name-to-class = “rule_name_id:scc_goal_name_id, rule_version:scc_goal_version” (optional)~~

Notes:
- profile title to be picked from actual profile
- name of the component-definition OSCAL folder is the component name (Resource column of CSV file), one for each

## Example CSV file

[CompDefFormat.csv](https://github.com/IBM/compliance-trestle/files/8958972/CompDefFormat.csv)

Revised: 2020-Sep-20, Vikas sees no need for: --profile, --rules-version, --property-name-to-class

**Comment by fsuits** [comment]
@degenaro and @vikas-agarwal76 can we confirm whether the spreadsheet conversion will generate a single comp-def file containing multiple components, or will there be only one component in each generated comp-def file?

**Comment by degenaro** [comment]
[component-definition-proposed.json.zip](https://github.com/IBM/compliance-trestle/files/9610338/component-definition-proposed.json.zip)

**Comment by degenaro** [comment]
- remove roles & such completely - `done`
- one control impl for each CIS profile (source) - `done`
- rules should be at source level - `done`
- for each source level, all rules should be in single property set - `done`
- "unknown" columns become another property for that rule & use user defined namespace
- two namespaces in config, one is "standard" and other is "user" 
- specify in config column name to class mapping (Rule Id and Rule Description, for now)
- in impl req for each control, there should be a set of properties one for each rule with Rule Id same except for remarks removed - `done`

**Comment by degenaro** [comment]
todo:

- honor column-name.class for user columns in spread sheet
- insist on required columns being present: 
> 1. Rule_Id
> 2. Rule_Description
> 3. Profile_Reference_URL
> 4. Profile_Description
> 5. Component_Type
> 6. Control_Mappings
> 7. Resource
- process the parameter columns, adding set parameters to produced CD
- check that if parameter is specified then all the required parts are present

hint: see best practices spread sheet in fs-cloud tools

**Comment by degenaro** [comment]
Control mapping column with id for a control will not have trailing _smt. Code should handle this case.

**Comment by degenaro** [comment]
When creating props for ia-5.1_smt.e, 3 rules are added that do not belong?

**Comment by HerbBoy** [comment]
any idea on the timeline to implement this?

**Comment by degenaro** [comment]
> any idea on the timeline to implement this?

Code PR'd with #1197 to develop branch. Plus a few PRs with follow-on fixes. There will likely be a new release of trestle next week incorporating same.

**Comment by degenaro** [comment]
Closed by PR #1197.
