### ISSUE TITLE
Add special handling for display-name and namespaces in properties

### ISSUE THREAD

**Issue by fsuits** [IBM/compliance-trestle#1161]
## Issue description / feature objectives
Currently set-parameters do not show properties or namespace in the markdown yaml header - but it is desirable to have the new "display-name" property visible and editable in the header.

In addition, when a new display name is added, an appropriate namespace should be assigned to it.

Furthermore, if any new property is added to a  control or part, a namespace should be assigned to it.
## Caveats / Assumptions
We want to provide the needed editing capability without making the yaml header too busy or confusing.

~~No namespace values will ever be listed for properties in the yaml header - and instead they will either be as set in the source .json, or they will be specified by two new command line options described below.~~

## Completion Criteria

1. Provide special handling of the display-name property in set-parameters by including it in the markdown yaml header along with name, values, etc.
2. The user may add or edit that display name
3. ~~Provide new command line option display-name-ns for profile-assemble to specify the namespace for *all* display-name properties in the control.  If that value is provided on the command line, all display-name properties will have that namespace in the assembled profile.~~
4. Also provide new command line option default-namespace to use as the namespace for any added property that doesn't already have a namespace specified.  ~~This only applies to profile-assemble.~~
5. If other -assemble commands should behave this way - please edit this list.

**Comment by vikas-agarwal76** [comment]
As discussed, during profile generate we will specify a CLI option default-ns. This would be shown in YAML header as a non-editable field. Currently we are assuming that "display-name" props of set-parameters will use this default ns. If in future they are using a different namespace then we will add another CLI option to specify the namespace for set-parameter properties (as we don't want to display the ns with each set-parameter property to keep set-parameter YAML headers simple).

For other properties at the control and subpart level, if the ns value is same as default-ns then the namespace for that property will not be shown in YAML header, else YAML header will show the specific ns for that property. If user creates or edits a property and don't specify a namespace in YAML header then the default-ns will be used during profile generate.
During profile-generate the default-ns CLI option will be optional. If not specified then the one from Makdown file will be used, else If specified then it will override the default namespace from markdown for all properties for which a namespace has not been explicitly specified in the YAML header. Properties with explicit namespace specified in YAML header will always have that namespace (not the default namespace).

**Comment by fsuits** [comment]
To summarize the desired behavior:

1. A new command line option default-namespace will be added to profile generate and assemble
2. In order to avoid applying it to arbitrary properties in the NIST catalog, such as sort-id, for set-parameters it will *only* apply to the special property, display-name.  And for set-parameters, the only property ever shown is display-name - and its namespace is never shown since it is always the default
3. The default-namespace value is specified in the TRESTLE_GLOBAL section of the header, which is not directly editable by the user and is only for informational purposes.  It is never read by the code.
4. The properties in the ADD_PROPS section of the header are assumed to be special to the user and can have a default namespace implied
5. When a md file is first generated, if default-namespace is specified then only properties with a namespace different from the default will appear in the markdown
6. If a property ever appears in the markdown, it will forever be unchanged during generate/assemble unless changed by the user
7. If you generate again with a different default namespace, none of the listed namespace values will change.  In other words, default namespace only and always applies to add-props that have no ns value shown
8. If you assemble with no default namespace given, only props with ns in the markdown will have ns assigned
9. If you assemble with default namespace given, all add-props with no ns in markdown will get the default value
