### ISSUE TITLE
Design and increase robustness for Trestle Plan.simulate

### ISSUE THREAD

**Issue by leninmehedy** [IBM/compliance-trestle#118]
## Issue description / feature objectives
Currently Trestle Plan.simulate is a bit naive since it executes and then rollback the changes in place.  Such approach could cause inconsistency if Plan encounters errors during simulation or fails to rollback during simulation. We either need to simulate in-memory or in a different temp directory.

## Completion Criteria
Plan.simulate should have robust error handling mechanism that guarantees that system cannot be in inconsistent state if simulation fails.

## Expected Behavior
Plan.simulate handles error during simulation robustly

## Actual Behavior
Plan.simulate cannot recover if rollback fails

**Comment by butler54** [comment]
Closing for #906
