### ISSUE TITLE
Pydanitc appears to no be correctly enforcing for some structures.

### ISSUE THREAD

**Issue by butler54** [IBM/compliance-trestle#12]
## Issue description / feature objectives
In investigating some typing behaviour I noticed that there are some issues with the pydantic models. when we have a structure such as
as
```json
{
"named-uuid-element_1" :{"component"},
"named-uuid-element_2":{"component"}
}
```
which results in an 'any type enforcement from the generated models (see two examples below)

```python
class ComponentDefinition(BaseModel):
    metadata: Metadata
    import_component_definitions: Optional[List[ImportComponentDefinition]] = Field(
        None, alias='import-component-definitions'
    )
    components: Optional[Dict[str, Any]] = None
    capabilities: Optional[Dict[str, Any]] = None
    back_matter: Optional[BackMatter] = Field(None, alias='back-matter')
```

```python
class InventoryItem(BaseModel):
    asset_id: str = Field(
        ...,
        alias='asset-id',
        description='Organizational asset identifier that is unique in the context of the system. This may be a reference to the identifier used in an asset tracking system or a vulnerability scanning tool.',
        title='Asset Identifier',
    )
    description: Description
    properties: Optional[List[Prop]] = None
    annotations: Optional[List[Annotation]] = None
    links: Optional[List[Link]] = None
    responsible_parties: Optional[Dict[str, Any]] = Field(
        None, alias='responsible-parties'
    )
    implemented_components: Optional[Dict[str, Any]] = Field(
        None, alias='implemented-components'
    )
    remarks: Optional[Remarks] = None

```

Expected behavior would be something closer to this:
```python
class ComponentDefinition(BaseModel):
    metadata: Metadata
    import_component_definitions: Optional[List[ImportComponentDefinition]] = Field(
        None, alias='import-component-definitions'
    )
    components: Optional[Dict[str, Component]] = None
    capabilities: Optional[Dict[str, Capability]] = None
    back_matter: Optional[BackMatter] = Field(None, alias='back-matter')
```
## Completion Criteria
Models are correctly generated.

**Comment by fsuits** [comment]
Using the latest code for datamodel-code-generator I get:

class ComponentDefinition(OscalBaseModel):
    metadata: Metadata
    import_component_definitions: Optional[List[ImportComponentDefinition]] = Field(
        None, alias='import-component-definitions'
    )
    components: Optional[Dict[str, Components]] = None
    capabilities: Optional[Dict[str, Capabilities]] = None
    back_matter: Optional[BackMatter] = Field(None, alias='back-matter')

So this appears to have been fixed and we just need to use the latest code.  The generated component.py does not have any "Any's" in it.  Let me know if I should check any other generated code.

**Comment by butler54** [comment]
Based on latest discussion: `datamodel-code-generator` has drifted further from what we need right now. 

Todos based on this:
- [ ] Create simple example for testing with the generator here: https://github.com/butler54/json-schema-testing-examples (Chris).
- [ ] Raise issue with generator folks to document issue.

- [ ] Create a script which corrects output from datamodel-code-generator 0.5.28 to the form in initial issue.

**Comment by butler54** [comment]
Note - Forward references may need to be retriggered based on updates.

**Comment by butler54** [comment]
Done.
