### ISSUE TITLE
Fix utility method to write/read Oscal List and Dict object to/from file correctly

### ISSUE THREAD

**Issue by leninmehedy** [IBM/compliance-trestle#120]
Currently we don't have a better way to read/write OSCAL List object like `List[Group]` or `Target-Definition.Targets` from/to a file that has contents like :

```
"groups":[
   {group1},
   {group2}
]
```

OR
```
"targets":[
   "uuid-1": {target},
   "uuid-2": {target},
]
```

**Expected behavior**
We should be able to write and read OSCAL List and Dict object to and from a file (JSON/YAML)

**Comment by brunomarq** [comment]
Also, it should be able to handle the cases where the alias of the root field in not easily inferable from the model class name such as `properties` and `Prop`, and `parameters` and `Param`.

**Comment by leninmehedy** [comment]
An example of error when we try to split `target-definitions.targets`

```
(venv) ➜  mytarget git:(feature/split-cmd) tsl split -f target-definition.yaml -e 'target-definitions.targets'  
...
  File "...trestle/core/models/elements.py", line 356, in oscal_wrapper
    wrapper_model = create_model(class_name, __base__=OscalBaseModel, **dynamic_passer)
  File "pydantic/main.py", line 844, in pydantic.main.create_model
  File "pydantic/main.py", line 244, in pydantic.main.ModelMetaclass.__new__
  File "pydantic/utils.py", line 99, in pydantic.utils.validate_field_name
NameError: Field name "dict" shadows a BaseModel attribute; use a different field name with "alias='dict'".
```
