### ISSUE TITLE
Create new type for uuid fields in Oscal models

### ISSUE THREAD

**Issue by aNebula** [IBM/compliance-trestle#122]
## Issue description / feature objectives
Currently uuids, in the pydantic models for OSCAL objects, are defined as `str` with constraints on the format.
This creates some issues when generating sample objects with some oscal models.
## Completion Criteria
`uuid` is a type of it's own, defined in a class and should be imported and used in other oscal models. 

## Expected Behavior
same as above
## Actual Behavior
currently `uuid` field in Oscal Models is a constrained string.

**Comment by butler54** [comment]
Closing as not a priority as it would be custom for trestle using fix_any.py as the mechanism used by NIST to specify UUID's is a constrained string.
