### ISSUE TITLE
new trestle task task cis-xlsx-to-oscal-catalog

### ISSUE THREAD

**Issue by degenaro** [IBM/compliance-trestle#1238]
## Issue description / feature objectives

Create new trestle task cis-xlsx-to-oscal-catalog

## Caveats / Assumptions

Should handle CIS Benchmarks:
- CIS Red Hat Enterprise Linux 8 Benchmark v1.0.0.1
- CIS RedHat OpenShift Container Platform Benchmark v1.2.0

See https://workbench.cisecurity.org/benchmarks?q=openshift&status=&sortBy=title&type=asc 
- search = openshift
- search = red hat enterprise

## Completion Criteria

trestle task implemented with 100% sonar coverage.

**Comment by vikas-agarwal76** [comment]
@degenaro should the task be called cis-xlsx-to-oscal-catalog as it handles CIS benchmarks?

**Comment by degenaro** [comment]
> @degenaro should the task be called cis-xlsx-to-oscal-catalog as it handles CIS benchmarks?

@vikas - yep. fixed. thx.

**Comment by degenaro** [comment]
[CIS_Red_Hat_Enterprise_Linux_8_Benchmark_v1.0.1.xlsx](https://github.com/IBM/compliance-trestle/files/9962416/CIS_Red_Hat_Enterprise_Linux_8_Benchmark_v1.0.1.xlsx)
[CIS_RedHat_OpenShift_Container_Platform_Benchmark_v1.2.0-2.xlsx](https://github.com/IBM/compliance-trestle/files/9962426/CIS_RedHat_OpenShift_Container_Platform_Benchmark_v1.2.0-2.xlsx)

**Comment by degenaro** [comment]
For CIS Red Hat Enterprise Linux 8 use 2.0.0.

**Comment by degenaro** [comment]
Fixed by #1270 .
