### ISSUE TITLE
Updates to SSP generate and assemble command

### ISSUE THREAD

**Issue by vikas-agarwal76** [IBM/compliance-trestle#1239]
## Issue description / feature objectives

After adding component definition authoring, the SSP authoring commands need to be updated. Following are some of the things that need to taken care of -

1. The SSP generate should take one or more CDs and a profile as input while generating the SSP markdown files. The SSP will be generated for that profile only. All components implementing that profile will be included in the SSP.
2. The SSP markdown files should show each of the components, their control responses, rule mapping, and implementation status from the CD. The per component implementation status should be editable in SSP. Rest of the content coming from CD will be non-editable.
3. There will be a default "this system" component representing the overall system for which the control response and implementation status will be editable in the markdown files.
4. control responses can be added either at control level or at statement level. Currently it is at statement level only.
5. Need to check what all props in YAML header are getting added by default and whether they are required or not such as x-trestle-fedramp-props.
6. Profile name should be shown in YAML header.
7. Rules and rule parameters. Rules for a given component and control should be included in SSP from CD. Where should the rules related data go in SSP. As part of component lists in system-implememntation->components->props, or in by-component->props for a control? All rules can be added at component level directly as we are planning to capture the rules in CD also at component level.
8. The set-parameter of implemented-requirements->by-components-set-parameters should be used to set the rule parameter value. This now needs to be done at control level for each component (in CD it was at component level). This value should be shown in SSP markdown YAML header for each component rule and should be editable.

**Comment by fsuits** [comment]
Some questions @vikas-agarwal76 :

1. Will the max number of CD's be small enough that a comma-delimited list on the command line is manageable?
2. Is there a need to specify a subset of the components to use - or will all always be used - if they have rules that apply to a control?
3. For question 4, fyi, the current implementation does allow specifying at the control level, but only if the statement has no parts.
4. I think the fedramp props should be ignored and removed until the fedramp implementation details are clarified.
5. I think the rules should go in at a high level, which means something high level in the ssp that has props.  A natural place would be the SystemImplementation - where the components are.  The SI role is "Provides information as to how the system is implemented."  While the ControlImplementation "Describes how the system satisfies a set of controls."  So the rules would be listed in the SI and the rules and values per control would be in ImpReqs of the CI.

**Comment by fsuits** [comment]
Currently we use `trestle author ssp-generate --profile --output`
This could change to `trestle author ssp-generate --profile --output --components "osco,foo,bar"`

**Comment by fsuits** [comment]
Questions:
Are rules distinct in each compdef?
Are rule_id's distinct in each compdef?
Are components distinct in each compdef?

**Comment by vikas-agarwal76** [comment]
rules are scoped to components, but can be same across components / CD.
rules related metadata will be captured at syste-impl->componenst->props
