### ISSUE TITLE
create tutorial for task csv-to-cd

### ISSUE THREAD

**Issue by degenaro** [IBM/compliance-trestle#1243]
## Issue description / feature objectives

Create a tutorial on using `task csv-to-cd`, similar to the other task tutorials.

## Caveats / Assumptions

N/A

## Completion Criteria

Tutorial works and instructs so that user can usefully employ the task.

**Comment by HerbBoy** [comment]
Might be overkill but figured I would add what I think would be valuable.

## Overall Definitions 
 - [ ] Definition of **Rule_Id** and what it is meant for/ties to OSCAL
 - [ ] Definition of **Rule_Description** and what it is meant for/ties to OSCAL
 - [ ] Definition of **Profile_Reference_URL** and what it is meant for/ties to OSCAL
 - [ ] Definition of **Profile_Description** and what it is meant for/ties to OSCAL
 - [ ] Definition of **Component_Type** and what it is meant for/ties to OSCAL
 - [ ] Definition of **Control_Mappings** and what it is meant for/ties to OSCAL
 - [ ] Definition of **Resource** and what it is meant for/ties to OSCAL
 - [ ] Definition of **Resource_Instance_Type** and what it is meant for/ties to OSCAL
 - [ ] Definition of **Parameter_Id** and what it is meant for/ties to OSCAL
 - [ ] Definition of **Parameter_Description** and what it is meant for/ties to OSCAL
 - [ ] Definition of **Parameter_Default_Value** and what it is meant for/ties to OSCAL
 - [ ] Definition of **Parameter_Value_Alternatives** and what it is meant for/ties to OSCAL
 - [ ] Definition of **Check_Id** and what it is meant for/ties to OSCAL
 - [ ] Definition of **Check_Description** and what it is meant for/ties to OSCAL
 - [ ] Definition of **Fetcher** and what it is meant for/ties to OSCAL
 - [ ] Definition of **Fetcher_Description** and what it is meant for/ties to OSCAL

## Examples
- [ ] Pictures of all possible column values could be.
- [ ] Picture of its corresponding JSON output.

## Future Ideas
- [ ] Column to support SSP mapping?

**Comment by degenaro** [comment]
@HerbBoy Could you expand a bit on `Column to support SSP mapping`? Thx!

**Comment by HerbBoy** [comment]
@degenaro 

I put it in as a like "if it makes sense" based on a response from @fsuits I am not sure it would make sense.

**Comment by degenaro** [comment]
Fixed by #1257
