### ISSUE TITLE
Assemble a Component Failing Date Validation

### ISSUE THREAD

**Issue by ride808** [IBM/compliance-trestle#1293]
## Describe the bug

I have a component that was generated by trestle through the CSV import. I then generated markdown documentation for that component, updated the .md files and then attempted to re-assemble that component using the updated markdown. This caused trestle to throw a validation error on the date format in the last-modified metadata.

## To Reproduce

1. Add a  component to trestle working structure with metadata.last-modified = "last-modified": "2023-02-15T19:29:24+00:00"

2. Generate markdown docs for that component: trestle author component-generate --name <componentname> --output /tmp

3. Reassemble from markdown documentation : trestle author component-assemble --name <componentname> -m /tmp/<componentname> --output /tmp --verbose

4. Get the following error:
```
trestle.common.model_utils:252 DEBUG: singular model type <class 'trestle.oscal.component.ComponentDefinition'> model alias component-definition
trestle.common.model_utils:266 DEBUG: not collection field type, malias: component-definition
trestle.common.model_utils:279 DEBUG: aliases to be stripped: set()
trestle.core.base_model:297 DEBUG: oscal_read content type FileContentType.JSON and alias component-definition from /framework/oscal/trestle/component-definitions/Kubernetes/component-definition.json
trestle.core.commands.author.component:96 ERROR: Assembly of markdown to component-definition failed: 1 validation error for Metadata
last-modified -> __root__
  invalid datetime format (type=value_error.datetime)
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/trestle/core/commands/author/component.py", line 142, in _run
    return self.assemble_component(
  File "/usr/local/lib/python3.9/site-packages/trestle/core/commands/author/component.py", line 201, in assemble_component
    ComponentAssemble.assemble_comp_def_into_parent(parent_comp, md_dir, context)
  File "/usr/local/lib/python3.9/site-packages/trestle/core/commands/author/component.py", line 248, in assemble_comp_def_into_parent
    metadata = com.Metadata(
  File "pydantic/main.py", line 342, in pydantic.main.BaseModel.__init__
pydantic.error_wrappers.ValidationError: 1 validation error for Metadata
last-modified -> __root__
  invalid datetime format (type=value_error.datetime)
```

Wondering if it's the csv import of a component that is creating a bad date time with respect to the oscal schema or if it's this bit of code in 1.2.0 (https://github.com/IBM/compliance-trestle/blob/v1.2.0/trestle/core/commands/author/component.py#L249)  and the "REPLACE_ME" lines causing the failure when a component is being built.
 
## Expected behavior

Expect the trestle author command to create a component definition

## Environment

OS: Linux RHEL7
Trestle version v1.2.0 based on OSCAL version 1.0.2
Python version: 3.9.10

**Comment by fsuits** [comment]
@ride808 sorry for the trouble here - and thanks for looking into it.  Yes that line of code is bad and it should insert a valid date there.  I will create a PR for it.  Thanks!

**Comment by fsuits** [comment]
@ride808 I looked into this and the code was wrong because it shouldn't have created metadata and last_modified in the first place.  I have created a PR to fix the issue:  https://github.com/IBM/compliance-trestle/pull/1294

I have added a test to cover the use case of adding a component to the markdown - which is what you need - but I may need to add more coverage.  Please give the PR a try if you can and let me know of any issues.  Thanks!

**Comment by ride808** [comment]
Thanks for the quick work of this issue @fsuits.  I don't have a dev environment setup currently to be able to test this PR out. Can't wait for the next release that will have this and the SSP assembly including components.
