### ISSUE TITLE
Intra-document validation for OSCAL artifacts.

### ISSUE THREAD

**Issue by butler54** [IBM/compliance-trestle#13]
## Issue description / feature objectives
The current pydantic models do not describe sufficiently the constrains required for a OSCAL schema.

NIST defines two sets of IDs
1) UUIDs: UUIDs must be globally unique within their object type. An acceptable solution is to test whether
a) UUIDs conform to required schema
b) UUIDs are unique (and error identifying the conflict if it exists)

Note: Many UUIDs are optional - I think we should have an option to populate more UUIDs as required.

2) NIST also defines ID fields. ID fields are scoped within the referenced document e.g. two catalogs can have colliding ID fields
Suggest two tiers of validation:
1) Compulsory: For an given object type (e.g. control) no id fields collide
2) Best-practice: For a given schema document where ID's are _defined_ no ID's collide

Note: (1) and (2) explicitly point to defining UUIDs / ID's and not references to UUIDs. 

The above functionality should be generic such that it can operate on any OSCAL object, however, presuming `uuid` and `id` are special fields that exist.

## Completion Criteria 
- Completed functionality
- Unit test coverage across all new code
- tested for catalog, profile, target, and SSP at a minimum.
- This functionality should work for both assembled and 'distributed' artifacts.
- validation should be able to operate over all files in a repository.

**Comment by leninmehedy** [comment]
```
trestle validate -f catalog.json --type uuid
- All UUID are in correct format
- All UUID is unique in the file
```
