### ISSUE TITLE
ocp-oscal-ssp repo automation setup

### ISSUE THREAD

**Issue by vikas-agarwal76** [IBM/compliance-trestle#1323]
## Issue description / feature objectives
Setup the automation in ocp-oscal-ssp repo for SSP creation based on compliance-trestle-testing/test-ssp-using-cd repo. The SSP generation should use the component definition from ocp-oscal-cd repo.

## Completion Criteria
1. setup automation for ocp-oscal-ssp repo on SSP creation
2. update workflow in ocp-oscal-profiles repo to push changes in profiles to SSP repo whenever a new release happens.
3. update workflow in ocp-oscal-cd repo to push changes in cd to  SSP repo whenever a new release happens.
4. Optional - setup Jinja template and related automation in ocp-oscal-ssp repo to generate Word document for SSP.

**Comment by enikonovad** [comment]
Done
