### ISSUE TITLE
Allow ssp-filter by implementation status

### ISSUE THREAD

**Issue by fsuits** [IBM/compliance-trestle#1332]
## Issue description / feature objectives
ssp-filter currently allows filtering based on controls (via profile) or components (via list of component names).  It could be useful to filter by implementation status - ideally a comma-separated list of status values
## Completion Criteria
Provide a new optional argument to `ssp-filter`:
`trestle author ssp-filter --implementation-status -is`
with value being a comma-separated list of status strings such as:
`implemented,partial`
Give error if one of the strings is not one of the allowed values for ssp implementation status.

**Comment by jpower432** [comment]
@fsuits If you consider this a good first issue, I would love to work on this feature.

**Comment by fsuits** [comment]
@jpower432 Sounds great!  Thanks for the offer.  Yes - please proceed.  I will update the completion criteria to specify the command line format that I think would work.  Let us know if you have any questions.  Thanks!
