### ISSUE TITLE
trestle author catalog-assemble infinite loop encountered

### ISSUE THREAD

**Issue by srmamit** [IBM/compliance-trestle#1349]
## Describe the bug

While running the following command, the execution never ends:
`trestle author catalog-assemble -v --set-parameters --markdown markdown/catalog --output catalog`

On investigating the markdown file, I could narrow it down to if markdown has sub-bullets to a markdown bullets, the catalog-assemble ends up going into infinite loop. Following snippet is where it would encounter infinite loop:
```
# Control id - Control Description. 

## Control Statement

A set of statements:
- Control Statement line 1. 
- Control Statement line 2.
	- Control Statement sub-bullet 1. 
OR
	- Control Statement sub-bullet 2.
```
OR
```
# Control id - Control Description. 

## Control Statement

A set of statements:
- Control Statement line 1. 
- Control Statement line 2.
	- Control Statement sub-bullet 1. 
	- Control Statement sub-bullet 2.
```

## Expected behavior

trestle author catalog-assemble exits with code 0 and assembles `catalog.json`

## Screenshots / Logs.

```
trestle.core.catalog.catalog_api:46 DEBUG: No catalog was provided in CatalogAPI init, generating a new one.
trestle.core.catalog.catalog_reader:116 WARNING: No group title found in controls for group <group_id>.  The title will be recovered if assembling into an existing catalog with the group title defined.

```

## Environment

- OS: macos
- Python version: Python 3.8.13
- Installed packages: `compliance-trestle==2.1.0`

**Comment by fsuits** [comment]
@srmamit please consult the tutorial [catalog etc. authoring](https://ibm.github.io/compliance-trestle/tutorials/ssp_profile_catalog_authoring/ssp_profile_catalog_authoring/) for an example of control markdown.

Each part should have an attached label like:

```
- \[a.\] Develop, document, and disseminate to {{ insert: param, ac-1_prm_1 }}:
```
The code should be fixed so it handles general input better, but if you make changes to your markdown so the labels are provided in the `\[a.\]` format it should work for you.

**Comment by srmamit** [comment]
Thank you for the tutorial link @fsuits , it was helpful in understanding the details.
The catalog I am working with is not a nist catalog, it is generated using trestle implementation of catalog, group, control, part and property. It uses part names that are not standard, I would guess standard part name is `statement` for using labels. I added the labels to non-standard parts but it did not provide the desired output. Labels seem to be populated when they are provided to part with name `statement` but not to my custom part names. If I rename my custom part names to `statement`, labels do show up.. but the part is different from `statement`.

**Comment by enikonovad** [comment]
Upon closer inspection, I think this is related to the tab character at the beginning of your `\t - Control Statement sub-bullet 1. `. Personally, I didn't even know you can put `\t` in the Github markdown. Of course nothing prevents you to putting tab in the local editor. 

In general even if you don't put `-[a]` it should work for adding parts to the statement. However, please note that adding parts in such a way only works for `## Control Statement` and `## Control objective` sections. For all others custom sections please use `### Part a.` format.

So I guess we can correct code to handle `\t` too or use spaces only
