### ISSUE TITLE
ForwardRef Error for "results_group" field in AssessmentResults

### ISSUE THREAD

**Issue by aslomoi** [IBM/compliance-trestle#138]
**Describe the bug**
When instantiating an AssessmentResults object the following error is shown:
```
Exception has occurred: ConfigError
field "results_group" not yet prepared so type is still a ForwardRef, you might need to call AssessmentResults.update_forward_refs().
```

**To Reproduce**
1. `import trestle.oscal.assessment_results as assessment_results`
2. Try write:  `ar = assessment_results.AssessmentResults(
        uuid=str(uuid4()), metadata=m, import_ap=ap, objectives=obj, results_group=results
    )` (where all other parameters are valid trestle objects)

**Expected behavior**
`ar` should not return an error and generate a trestle object

**Additional context**
Using compliance-trestle==0.2.0

**Comment by butler54** [comment]
@fsuits - Can you have a look at this?
