### ISSUE TITLE
Standardize public API for agile authoring

### ISSUE THREAD

**Issue by jpower432** [IBM/compliance-trestle#1426]
## Issue description / feature objectives

 Authoring logic is marked for internal use for generating and assembling SSPs. The other top-level models have public functions that can be used for this. Links to each function below in each model `Assemble` and `Generate` classes.

SSP functions
[Generate](https://github.com/IBM/compliance-trestle/blob/main/trestle/core/commands/author/ssp.py#L112)
[Assemble](https://github.com/IBM/compliance-trestle/blob/main/trestle/core/commands/author/ssp.py#L459)

Profile Functions
[Generate](https://github.com/IBM/compliance-trestle/blob/main/trestle/core/commands/author/profile.py#L115)
[Assemble](https://github.com/IBM/compliance-trestle/blob/main/trestle/core/commands/author/profile.py#L316)

Catalog Functions
[Generate](https://github.com/IBM/compliance-trestle/blob/main/trestle/core/commands/author/catalog.py#L98)
[Assemble](https://github.com/IBM/compliance-trestle/blob/main/trestle/core/commands/author/catalog.py#L165)

CompDef Functions
[Generate](https://github.com/IBM/compliance-trestle/blob/main/trestle/core/commands/author/component.py#L75)
[Assemble](https://github.com/IBM/compliance-trestle/blob/main/trestle/core/commands/author/component.py#L182)

## Caveats / Assumptions

- Certain logic may need to be private due to possibility of breaking changes or removal
- Since these functions are not strictly private, they can still be accessed and used 

## Completion Criteria

`SSPAssemble` and `SSPGenerate` have functions with high-level logic that are intended for public use

**Comment by vikas-agarwal76** [comment]
Some the Trestle CLI functionality is currently exposed via repository APIs through trestle / core/ repository.py Depending upon requirements generate / assemble functionality can also be exposed in a similar fashion.
