### ISSUE TITLE
Request to be added as a collaborator

### ISSUE THREAD

**Issue by afflom** [IBM/compliance-trestle#1456]
I would like collaborator (write) access to this repository.

- [x] I have read the [contributing guidelines][contributing]
- [x] I understand the responsibilities of a collaborator are to:
  - help review contributions to the compliance-trestle tool
  - help make & test releases
  - help promote the project

[contributing]: https://github.com/IBM/compliance-trestle/blob/main/CONTRIBUTING.md

**Comment by mrgadgil** [comment]
Invited you to be a collaborator

**Comment by afflom** [comment]
I've accepted. Thank you. Are there any other tasks that need to reference this open issue or can it be closed?

**Comment by mrgadgil** [comment]
No other action. we can close this issue. Thank you.
