### ISSUE TITLE
Objectives -> Objectives in AssessmentPlan

### ISSUE THREAD

**Issue by aslomoi** [IBM/compliance-trestle#149]
**Describe the bug**
Getting the following error in when validating an AssessmentPlan:
```
 field required (type=value_error.missing)
objectives -> objectives -> id
  field required (type=value_error.missing)
objectives -> objectives -> control-id
  field required (type=value_error.missing)
objectives -> objectives -> part
  field required (type=value_error.missing)
objectives -> objectives -> objectives
  extra fields not permitted (type=value_error.extra)
```

trestle has Objectives class with the following line:
`objectives: Optional[Union[Objective, Objective]] = None`

OSCAL defines it as:
`objectives: [0 to ∞]`

I believe trestle is expecting an object instead of a list... not 100% familiar with the syntax but perhaps it could be something like:
`objectives: Optional[List[Objective]] = None`

**To Reproduce**
1. Create a sample Objectives dictionary
2. Load it into `trestle.oscal.assessment_plan.Objectives.parse_obj(dict)`

**Expected behavior**
Should load without an error.

**Additional context**
Using v0.2.1

**Comment by butler54** [comment]
I believe based on my reading of the schema this should be
`objectives: Optional[Union[Objective, List[Objective]]] = None`

**Comment by aslomoi** [comment]
[OSCAL AP Schema](https://pages.nist.gov/OSCAL/documentation/schema/assessment-layer/assessment-plan/json-schema/#oscal-ap-json_objectives) defines it as:
*An array labeled objectives, containing objective objects, or a single objective object [0 to ∞]
A local definition of a control objective. Uses catalog syntax for control objective and assessment actions.*

The wording and the `[0 to ∞]` don't align to me... wouldn't the array be `[2 to ∞]`?

**Comment by butler54** [comment]
So it's saying you could have this (in pseudo-objects)

objectives: {objective_object}
or 
objectives: [{objective_object}, {objective_object}] 
but not 
objectives: [{objective_object}]

This approach was prevalent earlier versions of OSCAL across many objects. I'm wondering whether we should flag as the tried to simplify this down so if an array existed it existed.

**Comment by fsuits** [comment]
I believe it is creating Union[Objective, Objective] instead of Union[Objectives, Objective]

So this is related to recent change and is fixable.

**Comment by fsuits** [comment]
Actually the raw file output by modelgen has Union[Objective, Objective] - so that isn't the problem. I will look into it.
Union[Objective, Objective] is odd and that is before fix_any does anything...

**Comment by fsuits** [comment]
Here is a grep in the oscal dir *before* running fix_any that have this Union[A, A] thing.  Should they be Union[A, List[A]] ?

```python
assessment_plan.py:    objectives: Optional[Union[Objective, Objective]] = None
assessment_results.py:    objectives: Optional[Union[Objective, Objective]] = None
component.py:    annotations: Optional[Union[Annotation, Annotation]] = None
ssp.py:    annotations: Optional[Union[Annotation, Annotation]] = None
target.py:    annotations: Optional[Union[Annotation, Annotation]] = None
```

**Comment by fsuits** [comment]
I have added a global conversion of all Union[A, A] patterns to Union[A, List[A]] and can PR if that is the correct thing to do.

**Comment by butler54** [comment]
@fsuits that looks right to me. I'm going to add another PR as there is some inconsistent behaviour still in OSCAL.

**Comment by aslomoi** [comment]
If there is one Objective object, and it is placed in a list, would that not get incorrectly validated with that logic?

**Comment by fsuits** [comment]
Yes it would allow A, [A], [A, A]
Is there a way I can disallow [A] using Type notation?

**Comment by aslomoi** [comment]
conlist? https://pydantic-docs.helpmanual.io/usage/types/#constrained-types

**Comment by fsuits** [comment]
conlist looks good to me.  ssp.py already imports conint and constr.  I will look into it if the restriction is meant to be enforced:

A or [A,A,...] but not [A} - correct?  

That would be Union[A, conlist(A, min_items=2)]  I guess?

**Comment by butler54** [comment]
For a long term solution we should track here: https://github.com/usnistgov/OSCAL/issues/770
