### ISSUE TITLE
Assessment Plan object enforces optional STRVALUE field

### ISSUE THREAD

**Issue by wanitasherchan** [IBM/compliance-trestle#150]
**Describe the bug**
Working off compliance-trestle 0.2.1, get the following error when trying to validate Assessment Plan object. 

> assessment-plan -> objectives -> control-group -> 0 -> include-controls -> 0 -> STRVALUE
>   field required (type=value_error.missing)
> assessment-plan -> objectives -> control-group -> 0 -> include-controls -> 1 -> STRVALUE
>   field required (type=value_error.missing)
> assessment-plan -> objectives -> control-group -> 0 -> include-controls -> 2 -> STRVALUE
>   field required (type=value_error.missing)
> assessment-plan -> objectives -> control-objective-group -> 0 -> include-objectives -> 0 -> STRVALUE
>   field required (type=value_error.missing)
> assessment-plan -> objectives -> control-objective-group -> 0 -> include-objectives -> 1 -> STRVALUE
>   field required (type=value_error.missing)
> assessment-plan -> objectives -> control-objective-group -> 0 -> include-objectives -> 2 -> STRVALUE
>   field required (type=value_error.missing)

assessment-plan -> objectives -> control-objective-group -> 0 -> include-objectives -> 3 -> STRVALUE
  field required (type=value_error.missing)

**To Reproduce**

1. Create a sample Objectives dictionary
2. Load it into trestle.oscal.assessment_plan.Objectives.parse_obj(dict)
3. See error

**Additional context**
Using compliance-trestle 0.2.1

**Comment by butler54** [comment]
Appears to be an inconsistency in OSCAL documentation and schema see usnistgov/OSCAL#769

Labelling as 'won't fix' until we get a resolution with OSCAL.

**Comment by butler54** [comment]
Fixed by NIST.
