### ISSUE TITLE
Create localhost cache / fetcher.

### ISSUE THREAD

**Issue by butler54** [IBM/compliance-trestle#165]

**Comment by jeffdmgit** [comment]
Local fetcher with some tests in `feature/remote`. Still pending newer updates from `develop` though.

**Comment by jeffdmgit** [comment]
Also still pending implementation of get_raw, get_oscal and in_cache methods.

**Comment by jeffdmgit** [comment]
Done and with tests in `feature/remote` branch. Relative paths are not included, as they need reconsideration, I think.
