### ISSUE TITLE
Create generic https fetcher /cache.

### ISSUE THREAD

**Issue by butler54** [IBM/compliance-trestle#166]

**Comment by jeffdmgit** [comment]
Using the requests python library, we will have to document the fact that customizing the trusted CA bundle is via two env vars: 

> This list of trusted CAs can also be specified through the REQUESTS_CA_BUNDLE environment variable. If REQUESTS_CA_BUNDLE is not set, CURL_CA_BUNDLE will be used as fallback.

https://requests.readthedocs.io/en/latest/user/advanced/

I made the verify argument for requests.get() explicitly defaulting to None for security. Having it set to False would disable SSL certificate verification, and not setting it explicitly would leave the call relying on the default, which may change in some future release (if someone messes up).

Testing the authentication is pending, but basics are in: https://github.com/IBM/compliance-trestle/tree/feature/remote-jt-https
