### ISSUE TITLE
Setup DCO bot

### ISSUE THREAD

**Issue by aNebula** [IBM/compliance-trestle#17]
Setup DCO bot to check sign off https://github.com/probot/dco.
Setup PR merge template with checkbox to sign off DCO.

**Comment by butler54** [comment]
@aNebula - I have a feeling this requires us to change our workflow to one of the following:

1) A rebase based workflow e.g. :
https://medium.com/singlestone/a-git-workflow-using-rebase-1b1210de83e5
or https://blog.carbonfive.com/always-squash-and-rebase-your-git-commits/#:~:text=What%20is%20the%20squash%20rebase,%2Dto%2Ddate%20main%20branch. 

This would give us the advantage that DCO bot would be achievable. Only the last commit would be signed off on. It is also possible to enforce with github on the develop branch

2) Ask people to rebase as required (you can't avoid it)

3) But we don't care as we are going to be excluded as org members.

4) Not use / ensure squash and merge has an annotation in the PR (hard to enforce)>

**Comment by butler54** [comment]
I've attempted to set this up, however, it may be blocked at the moment.
