### ISSUE TITLE
structures where keys are meant to be UUID's are not structurally enforced in json-schema or validation

### ISSUE THREAD

**Issue by butler54** [IBM/compliance-trestle#181]
**Describe the bug**
The json schema (as an example) for component has a structure which looks like this:
```
components: {
 'uuid-string' : {'component object'},
 'uuid-string_2' : {'component object 2'},
}
```
The UUID's in this scenario are not enforced.

**Comment by butler54** [comment]
This will affect trestle add and trestle create.

**Comment by fsuits** [comment]
This is no longer relevant with OSCAL 1.0.0
uuid's only exist as named values
