### ISSUE TITLE
Document / formalize / Agree on key interactions with auditree

### ISSUE THREAD

**Issue by butler54** [IBM/compliance-trestle#195]
## Issue description / feature objectives
In discussions with the auditree team (in particular @drsm79 ) a tentative framework has been established to connect the auditree and trestle ecosystems.

A preliminary set of diagrams is here: 
[PNG](https://github.com/IBM/compliance-trestle/blob/develop/docs/assets/Canonical_trestle_auditree_workflows.png)
[DRAW.IO editable](https://github.com/IBM/compliance-trestle/blob/develop/docs/assets/canonical_trestle_auditree_workflows.drawio)

Given this there is a set of initial steps that need to be formalized.

1) Agreement on the interlock / workflow

2) Auditree (and/or auditree-harvest) under this workflow would be using the core `trestle.oscal` models Auditree team to provide feedback on missing required functionality / utilities.

**Comment by drsm79** [comment]
See also https://github.com/ComplianceAsCode/auditree-framework/issues/17
