### ISSUE TITLE
Rename trestle assembly to trestle publish or trestle distribute

### ISSUE THREAD

**Issue by butler54** [IBM/compliance-trestle#202]
## Issue description / feature objectives
Trestle assembly seems to be causing some issues - especially as it produces content into the 'dist' (or distribution / distribute) directory. 

Suggestion would be that we use trestle `publish` as that will have an easy pathway to provide further publishing outputs as optional extras (e.g. I could imagine `trestle publish --html` or trestle publish --openpages OP URL`

## Completion Criteria
- [ ] Docs refactored 
- [ ] classes and method names are refactored.

**Comment by butler54** [comment]
@fsuits - your feedback would be appreciated.

**Comment by fsuits** [comment]
Sounds good - except 'publish' usually means create a complete thing for consumption.  If this is instead outputting parts or incomplete objects maybe it is more 'export' or 'stage'?  I'm not clear on the main usage context.

**Comment by butler54** [comment]
I'm going to close this as I see the emergence of our semantic release workflow as the actual answer to this question and we will leave the current names as is.
