### ISSUE TITLE
As a platform owners I want to aggregate various independent SSPs/components into a 'larger' SSP.

### ISSUE THREAD

**Issue by butler54** [IBM/compliance-trestle#207]
## Issue description / feature objectives
SSP's define an audit scope. Depending on the nature of the profile and certification it may be advantageous to 'combine' SSPs /components into a larger SSP.

Depending on the context components may have their own SSP style object** (They may be for internal use by the platform provider rather than for external certification).

 
## Completion Criteria
Design and implement a workflow for allowing an aggreagation style conversion into a larger SSP.

**Comment by vikas-agarwal76** [comment]
Outdated.
