### ISSUE TITLE
Current SSP contains incorrect Dict[str, Any] types that should be corrected.

### ISSUE THREAD

**Issue by butler54** [IBM/compliance-trestle#228]
**Describe the bug**
A bug was found where there are two instances where a type of 'Dict[str, Any]' (at least in `develop`). Any causes downstream issues for model generation code written by @aNebula 

**To Reproduce**
Examine SSP models

**Expected behavior**
assess to see why they were not captured similar to other elements  / correct.

**Comment by butler54** [comment]
@fsuits I think we can close this?

**Comment by fsuits** [comment]
As I understand it this was fixed with my recent PR so yes it can be closed.
