### ISSUE TITLE
improve error messages in handling of Trestle Plan.simulate() exceptions

### ISSUE THREAD

**Issue by jeffdmgit** [IBM/compliance-trestle#243]
When Trestle Plan.simulate() encounters an error from a **trestle remove** operation, the former does not accurately describe the error encountered.

**To Reproduce**
1. Call **trestle remove** of a required, valid element from a valid .json file in a valid location that has been previously initialized for trestle.
4. See the error, which complains about the rollback but not about why the operation failed in the first place.

**Expected behavior**
A clear and concise error message that describes the reason for the failure.

**CLI session**

    $ trestle remove -f minimal_catalog.json -e catalog.metadata
    Remove failed (simulate()): Last stream position is not available to rollback to
    $

**Desktop (please complete the following information):**
 - OS: MacOS
 - Version 11.0.1

**Additional context**
The same nonspecific error message comes up in a few other failed operations, e.g., 

    $ trestle remove -f minimal_catalog.json -e catalog.metadata.responsible-parties.organisation
    Remove failed (simulate()): Last stream position is not available to rollback to
    (trestle)
    $ trestle remove -f minimal_catalog.json -e catalog.metadata.responsible-parties.organisation.party-uuids
    Warning: trestle remove does not support removing elements of a list: this removes the entire list
    Remove failed (simulate()): Last stream position is not available to rollback to
    $

**Comment by jeffdmgit** [comment]
This is related to #118.

**Comment by butler54** [comment]
Closing as removing simulate.
