### ISSUE TITLE
Content upload to openpages via OSCAL as a trestle task

### ISSUE THREAD

**Issue by butler54** [IBM/compliance-trestle#247]
## Issue description / feature objectives
Assumptions:
- Openpages exposes an OSCAL API
- Openpages internally addresses content via object UUIDs

Approach: 
Given an OSCAL object (e.g. a profile) and a desired Openpages host (+ credentials over http basic auth)

trestle task must first:
1) Build the assembly of OSCAL objects together.
2) For each of the dependencies from catalogs up check whether those dependencies are in openpages - this is to be done via the href structure (e.g. is it pointing to the provided host name?)
3) If not upload the content capturing the UUID it is stored in and log.
4) rewrite upstream objects referring to the object now in openpages.
5) Upload those new objects.

Example cli
`trestle tasks oscal-upload --file my_profile.json --host https://my_open_pages_host.com`

example href from profile 

```
ORIGINAL:
href: "file://catalogs/soc2.json"

NEW:
href: "https://my_open_pages_host.com/api/path/to/UUID_FOR_OBJECT"

**Comment by vikas-agarwal76** [comment]
https://my_open_pages_host.com/api/path/34343-sdsfd-3434

**Comment by vikas-agarwal76** [comment]
@butler54 I have the APIs ready for OpenPages. Will share details separately.

**Comment by butler54** [comment]
Okay given current status this is going in the icebox for now.

**Comment by butler54** [comment]
Closing out with no active demand for this.
