### ISSUE TITLE
Errors and warnings seen on screen when black cache is absent

### ISSUE THREAD

**Issue by linuxmonk** [IBM/compliance-trestle#258]
**Describe the bug**

Our code that calls trestle functions reports errors and warnings about failing to write grammar tables.

**To Reproduce**

* Remove `black` or it's cache directory from your machine
* Run trestle

The `datamodel-code-generator` that trestle depends on uses black (19.10b and < 20). The black 19.10b has a bug that creates the cache a bit too late if it is invoked via it's library (blib2to3). Issue references ([#1143](https://github.com/psf/black/issues/1143) and [#1223](https://github.com/psf/black/issues/1223)). #1223 fixes it but in 20.x of black.

Not sure if this affects its operation in anyway. I found this when I had cleaned up some of the software on my mac (not virtual env). I had removed black 

**Expected behavior**
No errors / warnings appear.

**Screenshots**
```
[INFO] :: blib2to3.pgen2.driver :: Generating grammar tables from /Users/saikiran/src/cdil/venv/lib/python3.8/site-packages/blib2to3/Grammar.txt
[INFO] :: blib2to3.pgen2.driver :: Writing grammar tables to /Users/saikiran/Library/Caches/black/19.10b0/Grammar3.8.0.final.0.pickle
[INFO] :: blib2to3.pgen2.driver :: Writing failed: [Errno 2] No such file or directory: '/Users/saikiran/Library/Caches/black/19.10b0/tmpurc39jo_'
[INFO] :: blib2to3.pgen2.driver :: Generating grammar tables from /Users/saikiran/src/cdil/venv/lib/python3.8/site-packages/blib2to3/PatternGrammar.txt
[INFO] :: blib2to3.pgen2.driver :: Writing grammar tables to /Users/saikiran/Library/Caches/black/19.10b0/PatternGrammar3.8.0.final.0.pickle
[INFO] :: blib2to3.pgen2.driver :: Writing failed: [Errno 2] No such file or directory: '/Users/saikiran/Library/Caches/black/19.10b0/tmpdqzih1yx'
```

**Desktop (please complete the following information):**
 - OS: MacOSX 

**Additional context**
None

**Comment by butler54** [comment]
@aNebula  - we ran into this issue before with some users. I believe you introduced datamodel-code-generator for some of the alias / case handling functionalities in the library.

Lets sync with @fsuits on #233 I think when that issue is completed it may allow us to avoid the issue (by using the latest version of datamodel code generator).
