### ISSUE TITLE
Centralize external configuration management for trestle

### ISSUE THREAD

**Issue by butler54** [IBM/compliance-trestle#265]
## Issue description / feature objectives
As a user I need a method that is known to be consistent to configure trestle

As a trestle developer I need a consistent methodology for setting up configuration.

As setup today there are two slightly divergent views of configuration
1) CLI flags only. CLI flags will manage some configuration but not all
2) trestle tasks that can read from default config location or from a user passed config file.

Using previous project inspiration configuration should be read in the following precedence
1) Environmental variables
2) config file
3) Declared code defaults.

Given the .trestle directory, and reading from the environment, it probably makes sense to only support the`ROOT_DIR/.trestle/config.ini` file.

What may be up for grabs is the file format used in our configuration file.

## Completion Criteria
1. Design and implement a config override mechanism where variables are declared once
2. Ensure mechanism is modular enough to support nesting as required (e.g. trestle tasks) - note that ini files with only one level of sections are not ideal.
3. Implement a model to allow developers to: 
a. To initialize global config
b. On how to access global configuration.

Note: Appears to be a preference for the injection methodology

**Comment by butler54** [comment]
Expecting that I will have work to do after this on trestle tasks to do a refactor.

**Comment by butler54** [comment]
Potential Libraries I have used before: 
 https://environ-config.readthedocs.io/en/stable/tutorial.html#getting-started
https://pydantic-docs.helpmanual.io/usage/settings/#parsing-environment-variable-values 

The pydantic option looks pretty nice. The only downside is the flat nature of the environment variables - but maybe that is a benefit.

**Comment by butler54** [comment]
Also a requirement: ideally the declaration of variables / config should be modular such that it is easy to identify the purpose and/or connected functionality.

**Comment by vikas-agarwal76** [comment]
This is not required now, since we have decided not to have a config.ini file.

**Comment by vikas-agarwal76** [comment]
not required.
