### ISSUE TITLE
Asymmetry between split and merge.

### ISSUE THREAD

**Issue by butler54** [IBM/compliance-trestle#285]
**Describe the bug**
In upgrading test data for merge with OSCAL 1.0 a couple of issues were noticed.

Rather than hand coding the dataset, once split passed it's tests split was used to run the stages as described within `tests/data/split-merge/README.md`

When this was performed split created a number of files that merge choked on. Specifically when examining stage 4
where one command which was executed was:

`trestle split -f ./groups.json -e 'groups.*.controls.*'` the file structure left a `groups.json` file which caused problems.

**Comment by aNebula** [comment]
@butler54 to be closed. #295
