### ISSUE TITLE
trestle assemble is not generating files where expected.

### ISSUE THREAD

**Issue by butler54** [IBM/compliance-trestle#327]
**Describe the bug**
Trestle assemble is meant to inject content into dist/OSCAL_MODEL_PLURAL/object_name.{json, yml}

At this point it is not.

**To Reproduce**
trestle init
trestle create catalog -n my-catalog
trestel assemble catalog -n my-catalog
ls dist/catalogs/
(No file)

**Expected behavior**
trestle init
trestle create catalog -n my-catalog
trestel assemble catalog -n my-catalog
ls dist/catalogs/
my-catalog.json

**Comment by aNebula** [comment]
@butler54 hmmm... so it was writing the file in the wrong place. It was putting a `dist/catalog.json` instead of `dist/catalogs/my-catalog.json', which needs to be fixed because where does `trestle assemble catalog -n my-catalog2` goes then?
