### ISSUE TITLE
As a trestle user - I would like trestle to provide devops pipelines for a set of common usecases

### ISSUE THREAD

**Issue by butler54** [IBM/compliance-trestle#341]
Primary usecase: Release management of trestle artifacts as they are code

e.g. automated validation on PR's)
- Automated assembles on release 
- Automated version tagging into the release
- Changelogs to the trestle repos

- Choice of devops system (github actions / travis / tekton?)

Potential other usecases:
- Publishing artefacts to 3rd party repositories
- executing workflows which collect information externally 
- integration with auditree workflows (such as osco-to-oscal).

**Comment by aNebula** [comment]
Starting with auto assemble, first.
Assumptions:
1. Git workflow- commit trestle project to a branch and merge in PR.
Stages of implementation:
1) Setup github repo with devops pipeline definition on `trestle init`. For first iteration, we can set this up manually.
2) Semantic versioning for auto release
3) Trigger assemble as check before executing release

Github Actions should do the job and it's also readily available with Github. Travis is okay, tekton might be overkill - let's see how Github Actions go.

**Comment by butler54** [comment]
Not relevant - provide demos instead.
