### ISSUE TITLE
website automation test hanging on windows

### ISSUE THREAD

**Issue by fsuits** [IBM/compliance-trestle#353]
Problem appears related to environment inheritance when using multiprocess.  Seems to work in CICD pipeline but not on my Windows 10 system.

**Comment by degenaro** [comment]
Sadly, I don't have windows readily available. Could you try adding the set_start_method like so:

```
def test_website_automation(tmpdir):
    """Test website boot and usability."""
    multiprocessing.set_start_method('spawn')
    p = multiprocessing.Process(target=_webserver)
    p.start()
```

**Comment by fsuits** [comment]
Unfortunately it still fails with 'mkdocs not found' when p.start() is invoked.  I assume the child process doesn't inherit the environment so at that point it does the import of mkdocs on line 23 and doesn't find it.  It may work if I globally set the PYTHONPATH but ideally that would be local to the environment.  If there is another way to launch the server it might avoid these issues.

**Comment by degenaro** [comment]
Please try a simplified+improved version: https://github.com/IBM/compliance-trestle/blob/fix/unit-test-website/tests/trestle/docs-serve/website_automation_test.py which works for me...but I'm not on Windows :-)
