### ISSUE TITLE
Allow -C option like git, to execute as if in a specified directory

### ISSUE THREAD

**Issue by fsuits** [IBM/compliance-trestle#359]
Most trestle commands require you to be in a trestle directory.  Like git we could allow an option similar to -C to perform the task as if in another directory without actually going there.

**Comment by fsuits** [comment]
This fits with the ongoing work to provide a manager class to keep track of trestle project root.  I believe the command chosen is -vr and that is fine.  -c is just the way git does it.

**Comment by vikas-agarwal76** [comment]
As discussed, we will go ahead with -tr option to specify the trestle root.
