### ISSUE TITLE
Trestle remote caching should support relative source paths on top of absolute paths

### ISSUE THREAD

**Issue by jeffdmgit** [IBM/compliance-trestle#365]
**Describe the bug**

At present, trestle remote caching of a local file will only support absolute paths. Relative paths are converted into absolute paths when processed, and this is reflected in the resulting cache path. 

**To Reproduce**
1. Touch a dummy file to establish a time reference when launching *find* later below.

        $ touch Makefile

1. Launch this test:

        $ pytest -vvv -k test_local_fetcher_relative tests/trestle/core/remote/cache_test.py

2. Locate the generated cache copy:

        $ find /private/var/folders/gd/p0zd_2_j4z54s99pb6wftr000000gn/T/pytest-of-jeffetan -newer Makefile -type f -name "*.json" -ls
        8646572290        8 -rw-r--r--    1 jeffetan         staff                 250 18 Feb 17:28 /private/var/folders/gd/p0zd_2_j4z54s99pb6wftr000000gn/T/pytest-of-jeffetan/pytest-88/test_local_fetcher_relative0/.trestle/cache/localhost/__abs__/__root__/private/var/folders/gd/p0zd_2_j4z54s99pb6wftr000000gn/T/pytest-of-jeffetan/pytest-88/test_local_fetcher_relative0/RMehYawyxfqQLZmV.json

3. Note that the path to the cached copy reflects the absolute source path: *.trestle/cache/localhost/**\_\_abs\_\_**/**\_\_root\_\_**/private/var/folders/gd/p0zd_2_j4z54s99pb6wftr000000gn/T/pytest-of-jeffetan/pytest-88/test\_local\_fetcher\_relative0/RMehYawyxfqQLZmV.json*. This does not reflect the caching spec.

**Expected behavior**
The caching specs require this structure instead, distinguishing clearly between absolute and relative paths for remote localhost objects:
```
├── .trestle
│   └──cache
│       ├── localhost (./ or file)
│       │   ├── __rel__
│       |   |   └── __parent__/__parent__/catalog.json
│       │   └── __abs__
│       |       └── /__root__/home/username/oscal/catalog.jon
```

**Desktop (please complete the following information):**
 - OS: MacOS
 - Version: 11.2.1

**Additional context**
Personally I recommend we keep the current behavior. I think that the relative path specs as above is ambiguous, because two distinct files may be referred to by identical relative paths, e.g., the relative path `../file.json` will refer to two different files depending on whether the current working directory when trestle was called was `/projectA/tmp` or `/projectB/tmp`:

```
/
├── projectA/
│   └──file.json
│   └──tmp/
│       ├── ..
├── projectB/
│   └──file.json
│   └──tmp/
│       ├── ..
```

**Comment by butler54** [comment]
I'm okay with this.
