### ISSUE TITLE
Support role-id constraints: Validator.

### ISSUE THREAD

**Issue by butler54** [IBM/compliance-trestle#369]
Nist has a constrained set of keys which express different roles in the role-id field (https://pages.nist.gov/OSCAL/documentation/schema/implementation-layer/component/json-schema/#global_responsible-party).

This enforces a constraint where in certain Dict[str, Object] pairs have keys which must be certain strings. 

Criteria for success:
1) A validator that enforces the criteria
2) generator functionality correctly identifies these scenarios and correctly generates the role-id.

**Comment by fsuits** [comment]
I did this as a more general form of NCName type validation.
The new mode of validation is ncname and the item is roleid.
If other items of type ncname need validation this can be extended.
No need to change the generator because the default string REPLACE_ME conforms to NCName.

**Comment by butler54** [comment]
Not required with OSCAL 1.0.0
