### ISSUE TITLE
As a trestle user on a Windows machine, paths to locally fetched objects on any drive should be supported, e.g., C:, D:, etc.

### ISSUE THREAD

**Issue by jeffdmgit** [IBM/compliance-trestle#372]
Windows allows for multiple drive letters like C: and D: on its filesystem to designate physical drives or distinct partitions. For trestle to cache a file with such a path, the caching directory structure should reflect this as it would the top-level directory on a non-Windows filesystem.

**Comment by butler54** [comment]
@fsuits  to connect with Jeff to understand whether issue still exists.

**Comment by fsuits** [comment]
Apparently this was resolved in Feb with commit 12b4d11021c3ff43e7d66c7637e976331b32320e

The fetcher uri allows properly specified windows paths with drive letters.

**Comment by fsuits** [comment]
Jeff confirmed this is now implemented.
