### ISSUE TITLE
Implement `trestle import`

### ISSUE THREAD

**Issue by brunomarq** [IBM/compliance-trestle#38]
## Issue description / feature objectives

Implement `trestle import` according to [specifications](https://github.com/IBM/compliance-trestle/blob/develop/docs/trestle-spec.md).

## Completion Criteria

Complete implementation and testing.

## Expected Behavior

- Contents of OSCAL model in imported file decomposed and placed in the expected folder as specification.

**Comment by jeffdmgit** [comment]
Pushed first working import with no decomposition, which is next to implement. Working in branch 'origin/feature/trestle-import-2'.

**Comment by jeffdmgit** [comment]
'coverage report' says 85% but verified in VS Studio Test Explorer that reported lines are actually covered by tests.
