### ISSUE TITLE
AssessmentResults results.local-definitions missing items

### ISSUE THREAD

**Issue by degenaro** [IBM/compliance-trestle#384]
**Describe the bug**
Seemingly, "inventory-items" and other keys are missing.

**To Reproduce**
Compare current AssessmentResults class LocalDefintions to [https://pages.nist.gov/OSCAL/documentation/schema/assessment-results-layer/assessment-results/json-model-map/](https://pages.nist.gov/OSCAL/documentation/schema/assessment-results-layer/assessment-results/json-model-map/). See screenshot below.

**Expected behavior**
Was looking to use inventory-items. Have hacked it into my copy of AssessmentResults for now.

**Screenshots**
![Screenshot from 2021-03-03 03-41-57](https://user-images.githubusercontent.com/520029/109783195-b92f4500-7bd7-11eb-8184-aff644fe715c.png)

**Comment by fsuits** [comment]
I confirm this is being dropped by fix_any.  I will look into it.

**Comment by degenaro** [comment]
Fixed by #386.
