### ISSUE TITLE
Implement `trestle split`

### ISSUE THREAD

**Issue by brunomarq** [IBM/compliance-trestle#39]
## Issue description / feature objectives

Implement `trestle split` according to [specifications](https://github.com/IBM/compliance-trestle/blob/develop/docs/trestle-spec.md).

## Completion Criteria

Complete implementation and testing.

## Expected Behavior

- Be able to split subcomponent of an OSCAL model including simple JSON object, arrays and objects of type additionalProperties.

**Comment by leninmehedy** [comment]
First version is done. Let's create bugs and feature requests.
