### ISSUE TITLE
As a developer I would like to have trestle maintain synchronisation with a GRC tool.

### ISSUE THREAD

**Issue by butler54** [IBM/compliance-trestle#395]
## Issue description / feature objectives
Developers may be contributing content to a document which is also managed at a GRC layer. An SSP would be a perfect example. A dedicated compliance team may review the final language, however, content may be repeatedly edited between a centralised (and presumed NOT to be coder) compliance function and a security/compliance focal on a service team.

In essence:

Trestle repo -> GRC -> trestle repo.

Assumptions:
1) The trestle content is edited on a PR based lifecycle. (whether a develop and deploy or a single branch)
   - Single branch is probably sufficient

Potential lifecycle (1) - most work on GRC system
User creates a PR
-> Content is validated.
-> PR approved

PR is merged 
-> GRC system is notified via a web-hook interface
-> GRC system authenticates and pulls content from the source repo

GRC system is updated:
-> GRC systems change is approved.
-> GRC system creates a PR to trestle REPO

User approves change in trestle repo.

This has some potential gaps in synchronisation that may occur
Other choices could include:
1) Trestle pushes straight to GRC system (this would mean the trestle user would be aware if a push failure occured and the potential syncronization issues),

2) Trestle owns interrogating GRC OSCAL api (assumption the GRC system presents an API which contains a full oscal object like a catalog).
- trestle dev-ops workflow would own generating a PR.

Other thoughts:
In the end you will always be reliant on good behaviour on both sides to ensure nothing goes terribly wrong. Approval workflows in git{hub|lab} must be similar to the GRC system.

**Comment by vikas-agarwal76** [comment]
We are using git workflows and Markdown for editing. No plans for GRC as of now.
