### ISSUE TITLE
Evaluate tooling options to xccdf conversion into json and/or converting xccd schema to json

### ISSUE THREAD

**Issue by butler54** [IBM/compliance-trestle#4]
XCCDF is another NIST standard for representing compliance information as part of scap (https://csrc.nist.gov/Projects/Security-Content-Automation-Protocol/Specifications/xccdf)

the definition of xccdf is xml only.

Evaluate options for representing xccdf in high fidelity as json including:
1) Creating a derivative json schema
2) Translation tools

Ideally these tools should be callable from trestle (aka python based).

Even more ideally: this should be represented as pydantic models.

Provide initial feedback then we will determine a path forward.

**Comment by butler54** [comment]
I think it might be interesting to look at https://github.com/martinblech/xmltodict or untangle which are generic converters.

**Comment by butler54** [comment]
This looks interesting as well.

**Comment by butler54** [comment]
Also sample relevant json: https://github.ibm.com/TMISHINA/xccdfparser/blob/master/example/result.xml

**Comment by butler54** [comment]
Current status so far: xccdf converters seem to be flakey and there is no standard.

Preferred workflow would be:
1) Convert .xsd to a json schema and bless it. (automatically??)
- Given the lack of change in xccdf manual effort will not hurt.
- Assumption xccdf 1.2


2) Use json schema to create json object model with pydantic

3) use xmltodict / json /etc to capture initial xccdf data and process into pydantic object model for json serialization?

**Comment by butler54** [comment]
@jeffdmgit to check https://github.com/highsource/jsonix-schema-compiler

**Comment by butler54** [comment]
https://github.com/benscott/xsdtojson

**Comment by jeffdmgit** [comment]
Just to round this off, a few tools were immediately discarded, but I did find a couple of interesting ones:
* *jsonix* has potential to do this well but would need reasonable effort to get things right with xml bindings (jaxb).
* *jgeXml* is able to generate valid json from the xsd but Chris verified that the result is not quite json schema.
* I can also use **xmllint** to validate TestResult but only after updating the xccdf schema with

        -    <xsd:import namespace="http://www.w3.org/XML/1998/namespace" schemaLocation="https://www.w3.org/2009/01/xml.xsd">
        +    <xsd:import namespace="http://www.w3.org/XML/1998/namespace" schemaLocation="http://www.w3.org/2009/01/xml.xsd">

Converting a valid TestResult into json then validating that against the json generated by *jgeXml* does not work (using the *jsonschema* library in python), e.g.,

        raise exceptions.SchemaError.create_from(error)
      jsonschema.exceptions.SchemaError: {'description': {'@xml:lang': 'en', '#text': 'Specifies an <xccdf:Value> or\n                        <xccdf:plain-text> element to be used for text substitution.'}, '$ref': '#/definitions/subType'} is not valid under any of the given schemas
    
      Failed validating 'anyOf' in metaschema['properties']['definitions']['additionalProperties']['properties']['properties']['additionalProperties']['properties']['items']:
          {'anyOf': [{'$ref': '#'}, {'$ref': '#/definitions/schemaArray'}],
           'default': True}
    
      On schema['definitions']['textWithSubType']['properties']['sub']['items']:
          {'$ref': '#/definitions/subType',
           'description': {'#text': 'Specifies an <xccdf:Value> or\n'
                                    '                        <xccdf:plain-text> '
                                    'element to be used for text substitution.',
                           '@xml:lang': 'en'}}
