### ISSUE TITLE
Stop split from splitting too far

### ISSUE THREAD

**Issue by fsuits** [IBM/compliance-trestle#422]
Prevent splits from going down to bare items like strings

**Comment by fsuits** [comment]
This has been implemented but needs reworking for the changes in 1.0.0.  The function split_is_too_fine has been disabled as have the corresponding tests.  It may be part of more extensive changes to element paths.

**Comment by butler54** [comment]
Draft PR submitted.

**Comment by fsuits** [comment]
This was also closed by issue #626 - which has been merged.
