### ISSUE TITLE
Create property schema for IBM Security & Compliance centre 'ready' OSCAL

### ISSUE THREAD

**Issue by butler54** [IBM/compliance-trestle#441]
In order for IBM Cloud S&CC to support OSCAL - a set of extra constrains is required when articulating results to be sent to the system. 

Specifically:
- Standardization of inventory format properties (e.g. fixed classes /names)
- Standardization of result format properties (e.g. fixed classes /names)

**Comment by butler54** [comment]
Actions: 
- [ ] Update documentation with latest changes
- [ ] Ensure information is in ibm.github.io website
- [ ] Cross reference with SCC links when available.

**Comment by vikas-agarwal76** [comment]
Updated documentation with latest changes for Tanium

**Comment by vikas-agarwal76** [comment]
feat/third-party-schema branch

**Comment by butler54** [comment]
Depends on #596
