### ISSUE TITLE
Benchmark time to complete tanium-to-oscal transformation (in-memory)

### ISSUE THREAD

**Issue by butler54** [IBM/compliance-trestle#442]
**Trestle consumer request**

There is a consideration of using trestle within an synchronous API. For this we need to understand the performance characteristics for the tanium to OSCAL conversion:

Given a tanium file of N rows (already in memory) compute the mean time to get the OSCAL return object as a string in memory.

**Comment by butler54** [comment]
@degenaro - @vikas-agarwal76 will fill you in.

**Comment by butler54** [comment]
Based on further discussion:
Scale the size until conversion is ~10-15 seconds and report incremental execution cost.

**Comment by butler54** [comment]
Assumption: Code is executing in a single thread.

**Comment by vikas-agarwal76** [comment]
Experiments done. Here is the raw output.
Starting experiments...
Num experiments with different input file sizes: 10
Num Iter per exp: 10, Repeat: 3
*****Experiment: 1, Num input records: 3500
Total time: 14.068124795, Per iteration time: 1.4068124794999999
Total time: 14.408170002999999, Per iteration time: 1.4408170002999998
Total time: 14.080973725, Per iteration time: 1.4080973724999999
Avg time per iter: 1.4185756174333333
*****Experiment: 2, Num input records: 7000
Total time: 28.623958807, Per iteration time: 2.8623958807000003
Total time: 28.646513626, Per iteration time: 2.8646513626
Total time: 28.844808497000002, Per iteration time: 2.8844808497
Avg time per iter: 2.8705093643333335
*****Experiment: 3, Num input records: 10500
Total time: 43.44882419000001, Per iteration time: 4.344882419000001
Total time: 43.332940331, Per iteration time: 4.3332940331000005
Total time: 43.21877510799999, Per iteration time: 4.3218775107999985
Avg time per iter: 4.333351320966666
*****Experiment: 4, Num input records: 14000
Total time: 57.99442005900005, Per iteration time: 5.799442005900005
Total time: 57.96020634300004, Per iteration time: 5.796020634300004
Total time: 58.119785096999976, Per iteration time: 5.811978509699998
Avg time per iter: 5.802480383300002
*****Experiment: 5, Num input records: 17500
Total time: 73.05365321099998, Per iteration time: 7.305365321099998
Total time: 72.61369471400002, Per iteration time: 7.261369471400002
Total time: 73.0667790299999, Per iteration time: 7.306677902999991
Avg time per iter: 7.291137565166664
*****Experiment: 6, Num input records: 21000
Total time: 87.92980062599997, Per iteration time: 8.792980062599998
Total time: 90.98647173099994, Per iteration time: 9.098647173099994
Total time: 87.11498364900001, Per iteration time: 8.7114983649
Avg time per iter: 8.867708533533332
*****Experiment: 7, Num input records: 24500
Total time: 102.78970052499994, Per iteration time: 10.278970052499995
Total time: 103.01130644399996, Per iteration time: 10.301130644399995
Total time: 102.82545354900003, Per iteration time: 10.282545354900003
Avg time per iter: 10.28754868393333
*****Experiment: 8, Num input records: 28000
Total time: 118.06711718499992, Per iteration time: 11.806711718499992
Total time: 117.46000645599997, Per iteration time: 11.746000645599997
Total time: 122.81419615599998, Per iteration time: 12.281419615599997
Avg time per iter: 11.944710659899997
*****Experiment: 9, Num input records: 31500
Total time: 134.76585881699998, Per iteration time: 13.476585881699998
Total time: 133.0149855919999, Per iteration time: 13.30149855919999
Total time: 131.9767804820001, Per iteration time: 13.19767804820001
Avg time per iter: 13.325254163033334
*****Experiment: 10, Num input records: 35000
Total time: 148.37022122000008, Per iteration time: 14.837022122000008
Total time: 148.61654595899972, Per iteration time: 14.861654595899973
Total time: 149.29369993399996, Per iteration time: 14.929369993399996
Avg time per iter: 14.876015570433324
Done.

**Comment by vikas-agarwal76** [comment]
Num   Recrods (Observations) | Time (in Secs)
-- | --
3500 | 1.419
7000 | 2.871
10500 | 4.333
14000 | 5.802
17500 | 7.291
21000 | 8.868
24500 | 10.288
28000 | 11.945
31500 | 13.325
35000 | 14.876

![image](https://user-images.githubusercontent.com/75295756/113874203-2d5e9900-97d3-11eb-99f0-9df8cfd02275.png)

**Comment by vikas-agarwal76** [comment]
Here are the results comparing with and without json serialization and deserialization.


Num   Records (Observations) | With json ser | Without JSON ser
-- | -- | --
3500 | 1.419 | 0.82
7000 | 2.871 | 1.74
10500 | 4.333 | 2.641
14000 | 5.802 | 3.692
17500 | 7.291 | 4.731
21000 | 8.868 | 5.871
24500 | 10.288 | 6.859
28000 | 11.945 | 7.606
31500 | 13.325 | 8.422
35000 | 14.876 | 9.466

![image](https://user-images.githubusercontent.com/75295756/114065006-d4b4fc00-98b7-11eb-9803-fdc09d8a08cb.png)

**Comment by butler54** [comment]
![callgraph](https://user-images.githubusercontent.com/19358775/114362258-7b501400-9bba-11eb-82a0-6c95173861b0.png)

Call graph for w/o Json serialization. Had a bit of a dig into the code and some reading, however, my suggestion is we first let @degenaro finish refactoring for the transform API before we start refactoring.
