### ISSUE TITLE
Remove bad Any's in the Oscal python models

### ISSUE THREAD

**Issue by fsuits** [IBM/compliance-trestle#459]
The python oscal models have always had an Any for biblio that cannot easily be fixed.

But the recent NIST update has introduced Any's in assessment_plan, assessment_results and poam of the form:

    class OscalAssessmentCommonSelectControlById(OscalBaseModel):
        __root__: Any

and

    include_all: Optional[Dict[str, Any]] = Field(
        None,
        alias='include-all',
        description='A key word to indicate all.',
        title='All',
    )

There is 1 root Any in assessment_plan, 3 in assessment_results, and 2 in poam.

There are 3 include_all Any's in assessment_plan, 3 in assessment_results, and 1 in poam.

These should all be replaced by the proper typing in a form of fix_any - or they may get fixed in a combination of new NIST and new datamodel-codegen.

**Comment by fsuits** [comment]
With the recent changes in 1.0.0, the only Any's are due to IncludeAll.  There are no root Any's of the nature described here anymore.

**Comment by butler54** [comment]
This is currently okay.
