### ISSUE TITLE
Deep run time type conversion for pydantic models across different pydantic 'modules' representing OSCAL objects.

### ISSUE THREAD

**Issue by butler54** [IBM/compliance-trestle#46]
## Issue description / feature objectives
Current approach for `trestle` is to create one module of modules per OSCAL schema. OSCAL schemas are overlapping in nature - which means we have actual or near duplicate object definitions in various modules.

Discussion with NIST team (https://github.com/usnistgov/OSCAL/issues/731) is unresolved and we are unlikely to see shared models in the short term w/o changing our model structures.

This gives us a requirement: I want a simple interface to do a deep copy of pydantic models across 'module spaces'.

E.g. Humans know that `trestle.oscal.catalog.Metadata` is equivalent to `trestle.oscal.profile.Metadata` and should be deep copy-able, however, the pydantic type enforcement cause errors.

Ideally what we would want to have is something _similar_ in functionality to this:

```python

import trestle.oscal.catalog as c
import trestle.oscal.profile as p

my_catalog: c.Catalog = catalog_from_disk_or_elsewhere


# Following line does not work
# profile: p.Profile = p.Profile(metadata=my_catalog.metadata)

# Something like this would be nice(ish)
 profile: p.Profile = p.Profile(metadata=my_catalog.metadata.cast_to(p.Metadata))
# or 
 profile: p.Profile = p.Profile(metadata=my_catalog.metadata.cast_to(p))

```

## Completion Criteria
Deep copy routine completed for a generic usecase including associated unit tests.

## Expected Behavior
See above plus the notes below

1. It should be recursive - Field introspection in pydantic should allow the exploration of the underlying objects.
1. By default inconsistent fields should throw exceptions - allowing users to specially program / handle
1. It may be worth exploring option behaviour which is 'permissive' / opportunistic.
1. At this point there should be no assumptions on `transformation` in the workflow. Generic copy capabilities come fir

## Actual Behavior
 - None - users have to deep code copies at this current point in time.

**Comment by butler54** [comment]
@leninmehedy - TBD let's discuss.

**Comment by aNebula** [comment]
@butler54 Also note that `component` model exists under both `ssp` schema and `component` schema, and are not quite the same.
`ssp.Component` doesn't have `control-implementations` and `component.Component` has`annotations`, `status`.

What should be done when they are not the same?
TBD - @brunomarq
