### ISSUE TITLE
Update OSCAL result deserialzation

### ISSUE THREAD

**Issue by vikas-agarwal76** [IBM/compliance-trestle#487]
After tanium was updated to transformer API the Results object deserialization is taking a lot of time than what it was taking earlier. Update the Result wrapping into outer json object and deserialzation to improve the time.

**Comment by butler54** [comment]
I believe we fixed this? @vikas-agarwal76

**Comment by vikas-agarwal76** [comment]
yes. this was fixed. We can close this

**Comment by vikas-agarwal76** [comment]
yes. this was fixed. We can close this
