### ISSUE TITLE
Change interface to transformers to take in a bytestring

### ISSUE THREAD

**Issue by butler54** [IBM/compliance-trestle#491]
Reported by @blinxguna - The interface to transformers uses a string type on `transformer.transform()`. An issue has been identified that where when consuming data over API new line feeds are escaped by POST APIS. This creates an issue in terms of inconsistency between cli and api based ops.

Refactor ResultsTransformer to read in bytestrings (including tanium IO).

**Comment by vikas-agarwal76** [comment]
I found that the following code works

@app.route(‘/hello’, methods = [‘POST’])
def hello_world():
    tool = request.args.get(‘tool’)
    print(tool)
    blob: str = request.get_data()
    lines = blob.splitlines()
    for line in lines:
        print(json.loads(line))
    return str(len(lines))

if we get the request body using request.get_data() and do not explicitly convert it to string using str(request.get_data) and we use blob.splitlines() to split each record it works…

but if I change to lines = blob.split(‘\n’) it does not work . it says TypeError: a bytes-like object is required, not ’str

so if we change the tanium code to use blob.splitlines() instead of blob.split(‘\n’) and the API passes the whole body as it is without doing any conversion to string … it should work

if the API explicitly converts the body to string using str(request.get_data()) then splitlines just gives one line…

**Comment by vikas-agarwal76** [comment]
splitting using splitlines() function is more robust as newlines on different systems have variations such as ‘\n’ ‘\r\n’, etc.. which all will be handled by splitlines() but not if we explicitly use split(‘\n’)

**Comment by vikas-agarwal76** [comment]
Actually just decoding the bytearray as utf-8 encoding would work without requiring any changes in transformer code...
```
    blob = request.get_data()
    blob = str(blob, encoding=‘utf-8’)
    lines = blob.split(‘\n’)
```
or lines = blob.splitlines()
both split techniques work on blob

**Comment by vikas-agarwal76** [comment]
Just had a chat with Gunendra. Changing the API code to use -

blob = str(blob, encoding=‘utf-8’)

and then calling the transform API with decoded string works.

Hence, no change is required in transformer interface. But it is better to use splitlines() instead on split('\n') in transformer to make the code robust.

**Comment by degenaro** [comment]
We can easily handle string or bytes like so:
```
t_blob = AnyStr
   
 def transform(self, blob: t_blob) -> Results:
        """Transform the blob into a Results."""
        """
        The expected Tanuim blob is a string or bytes that contains embedded lines, each ending with line-end.
        Each embedded line is a json string.
        """
        results = Results()
        if type(blob) == 'bytes':
            sdata = blob.decode('utf-8')
        else:
            sdata = blob
        lines = sdata.splitlines()
```
I will create PR and deliver accordingly. Would we really need any encoding other than utf-8??

**Comment by vikas-agarwal76** [comment]
@degenaro Gurender is decoding the bytearray in API code to utf-8 string and then calling our transform API. So let's not change the API signature. Conversion from anything to string should be done outside the transformer API.

But you can update code to use splitlines().

**Comment by degenaro** [comment]
OK. Will make splitlines() change only. Since not a blocker, will deliver with together with upcoming class name revisions change PR likely next week.

**Comment by fsuits** [comment]
This is now in release 0.14.3
