### ISSUE TITLE
Support ResultsTransformer interface for osco-to-oscal transformer.

### ISSUE THREAD

**Issue by degenaro** [IBM/compliance-trestle#504]
## Issue description / feature objectives

The osco-to-oscal transformer should implement the ResultsTransformer interface.

## Completion Criteria

- The transform works correctly using the ResultsTransformer interface.
- 100% code coverage test cases.

**Comment by butler54** [comment]
I think this is completed @degenaro can you confirm?

**Comment by degenaro** [comment]
Closed by #532.
