### ISSUE TITLE
validation of duplicate uuids in memory won't catch duplicates within same dict in file

### ISSUE THREAD

**Issue by fsuits** [IBM/compliance-trestle#505]
Any validation done in memory after loading json will be blind to duplicates in a dict in the file.

Need special json/yaml reader to catch this possibility.

The current duplicate validator can then check duplicates globally in the file.

This is particularly an issue with toy files used to learn trestle, and could happen after splitting, making changes, and merging.

**Comment by fsuits** [comment]
With the changes in OSCAL 1.0.0 there may be less need to check for duplicates in memory.  But lists in memory may have duplicate uuid's.  So there may not be need to check for this when reading json - but there is still need to check the oscal version at the json_read level.

**Comment by butler54** [comment]
Issue TBC w/o dealing with OSCAL 1.0.0 version testing (issue #588).

**Comment by vikas-agarwal76** [comment]
Done.
