### ISSUE TITLE
Replace use of standard xml library with defused xml

### ISSUE THREAD

**Issue by butler54** [IBM/compliance-trestle#535]
## Issue description / feature objectives
The plain old xml library within python has risks (see: https://docs.python.org/3/library/xml.html#defusedxml-package) which make it unsafe to use from a service availability perspective.

Replace functionality with defused xml capability to ensure safety against xml bombs and other adverse structures.

## Completion Criteria
- [ ] All instances of xml parsing leverage defused xml within the code base.

**Comment by degenaro** [comment]
Closed in #532.

**Comment by butler54** [comment]
Quick review for completeness required.
