### ISSUE TITLE
Support to validate different / multiple conformance objectives.

### ISSUE THREAD

**Issue by butler54** [IBM/compliance-trestle#54]
## Issue description / feature objectives
Fedramp (as an example) have defined expected values / conformance within the OSCAL schema (see here:https://github.com/GSA/fedramp-automation/blob/master/documents/FedRAMP_OSCAL_Registry.xlsx)
 It would be a good feature if validation could be extended with a conformance format of some type.

**Comment by butler54** [comment]
Will add more details - a placeholder for now.

**Comment by butler54** [comment]
Based on discussion with Anca this is a need. The question is what language with which we express constraints. This looks promising https://github.com/amer-ali/jsontron - much like schematron would look like for xml.

**Comment by butler54** [comment]
This issue is on validate an acceptable design only. I've tagged it for Sprint 2 with Shaila and Jeff both on this. I think this may be more work than we think.

**Comment by shaila309** [comment]
@jeffdmgit Here is the jsontron tutorial as discussed: https://amer-ali.github.io/jsontron/Jsontron-tutorial-v1.pdf

**Comment by shaila309** [comment]
**Related issues open in usnistgov/metaschema**

1. Tracker Issue for Metaschema work: https://github.com/usnistgov/OSCAL/issues/633
2. Integrating XSLT-M4 Metaschema into OSCAL repo: https://github.com/usnistgov/OSCAL/issues/721

**Summary (need-to-be-verified)**
Extra metadata constraint validation is done on XML using schematron.
To validate extra metadata constraint on JSON, first the JSON is converted to equivalent XML and then schematron is applied on that.

**Comment by shaila309** [comment]
**Data validation using jsontron https://github.com/amer-ali/jsontron - Example**

- Goal: All properties MUST be of ns (namespace) "IBM"

- Sample JSON to validate 
_sample-OSCAL-assessment-result-observation.json_
```json
{
  "sample_ar_observation":{
    "uuid":"",
    "title":"CIS CentOS Linux 7 Benchmark 2.2.0:1.1.1.1, 192.168.122.4, Sep 11, 2020 at 5:12 PM AEST",
    "description":"IBM S&CC scan, CIS CentOS Linux 7 Benchmark 2.2.0:1.1.1.1, 192.168.122.4, 2020-09-11T17:12:00+1000",
    "properties":[
        {
            "ns": "IBM",
            "class": "id",
            "name": "scan",
            "value": "SGA Centos validation - Sep 11, 2020 at 5_12 PM AEST"
        },
        {
            "ns": "IBM",
            "class": "id",
            "name": "profile-name",
            "value": "CIS CentOS Linux 7 Benchmark 2.2.0"
        },
        {
            "ns": "IBM",
            "class": "id",
            "name": "rule",
            "value": "1.1.1.1"
        }
    ],
    "annotations": [
    ],
    "observation-methods":[
        "TEST-AUTOMATED"
    ],
    "subject-references": [
        {
            "uuid-ref":"(may not apply unless part of a complete OSCAL SAR/SSP -- but note that OSCAL *requires* this)",
            "type":"component",
            "title":"192.168.122.4",
            "props":[
                {
                    "ns": "IBM",
                    "class": "id",
                    "name": "IT-resource",
                    "value": "192.168.122.4"
                },
                {
                    "ns": "IBM",
                    "class": "id",
                    "name": "control-target",
                    "value": "centos"
                }
            ]
        }
    ],
    "evidence-group": [
        {
            "href":"",
            "description":"S&CC scan result",
            "properties":[
                {
                    "ns": "IBM",
                    "class": "info",
                    "name": "actual-value",
                    "value": "[{\"name\":\"cramfs\", \"status\":\"disabled\", \"value\":\" install /bin/true \"}]"
                },
                {
                    "ns": "IBM",
                    "class": "info",
                    "name": "expected-value",
                    "value": "Mounting of cramfs filesystems should be disabled"
                },
                {
                    "ns": "IBM",
                    "class": "result",
                    "name": "result",
                    "value": "PASS"
                },
                {
                    "ns": "IBM",
                    "class": "info",
                    "name": "detail",
                    "value": "Mounting of cramfs filesystems is disabled"
                }
            ]
        }
    ]
}
}
```

- Sample rule to be used by jsontron 
_rule-OSCAL-assessment-result-observation.json_
```json
{
  "schema": {
    "id": "OSCAL AR Observation Rules",
    "title": "Schematron Semantic Validation",
    "schemaVersion": "V1",
    "queryBinding": "jsonpath",
    "pattern": [
      {
        "id": "observation_properties",
        "title": "OSCAL AR Observation Properties",
        "abstract": false,
        "rule": [
          {
            "id": "ns_ibm",
            "abstract": false,
            "context": "$.sample_ar_observation.properties.*",
            "assert": [
              {
                "id": "assertid1",
                "test": "jp.query(contextNode, '$..ns') == 'IBM'",
                "message": "Assert 1: All observation properties MUST be of ns (namespace) IBM"
              }
            ]
          }
        ]
      }
    ]
  }
}
```

- Command
_node $JSONValidator -i sample-OSCAL-assessment-result-observation.json -r rule-OSCAL-assessment-result-observation.json -d_

- Output

`
Starting Semantic Validation .........
Parsing Pattern: observation_properties
1 Pattern(s) Requested. 1 Pattern(s) Processed. 0 Pattern(s)  Ignored.
**** THIS INSTANCE IS SEMANTICALLY VALID ****
Completed Semantic Validation .........
Total Errors Found: 0
Total Warnings Found: 1
Total Validations: 3
Total Failed Assertions: 0
Full Validation Report : 
Report {
  errors: [],
  warnings: [
    {
      schInstance: [Object [global]],
      schema: [Object],
      attribute: 'Phase',
      message: 'Parsing Warning. No phase found ',
      detail: "This schema doesn't have any phase defined . All Patterns will be processed."
    }
  ],
  validations: [
    {
      schRule: [Object],
      ruleContext: [Array],
      assertionid: 'assertid1',
      assertionTest: "jp.query(contextNode, '$..ns') == 'IBM'",
      message: 'successful',
      assertionValid: true
    },
    {
      schRule: [Object],
      ruleContext: [Array],
      assertionid: 'assertid1',
      assertionTest: "jp.query(contextNode, '$..ns') == 'IBM'",
      message: 'successful',
      assertionValid: true
    },
    {
      schRule: [Object],
      ruleContext: [Array],
      assertionid: 'assertid1',
      assertionTest: "jp.query(contextNode, '$..ns') == 'IBM'",
      message: 'successful',
      assertionValid: true
    }
  ],
  finalValidationReport: [],
  valid: true
}
`

**Comment by shaila309** [comment]
Approaches:

Integrate external tool like jsontron - No - lots of dependancy
Develop min validator by ourselves like jsontron - lots of parsing
Define as factory style class - build - python abstract class interface - passes object - preferred

**Comment by butler54** [comment]
<img width="960" alt="validate-discussion" src="https://user-images.githubusercontent.com/19358775/97121805-20923f80-1775-11eb-88d8-61f567361859.png">
Attachched image based on latest discussion.

**Comment by shaila309** [comment]
- There can be different types of conformance validators for different parties like ibm, fedramp, etc. as well as a default cross structural conformance validator.
- The expected order of operation: basic oscal schema validation, cross id (uuid) uniqueness validation, default cross structural conformance validator, selected conformance validator (ibm, fedramp, etc.)
- The overlay of validators on top of basic socal schema validator can be optional.
- Validation can happen both Inter document and intra document.

From validation perspective, the expected scenario is: 
- Input: one or more oscal object
- Output: pass / fail
- Log: the reason behind the output 

To be discussed:
- How do we mention which validator we want to use if there are many?
- What will be the interface to specify the constraints?

**Comment by shaila309** [comment]
@butler54 @jeffdmgit Here is the response from the OSCAL team on the issue of Validating extra-schema constraints over JSON: https://github.com/usnistgov/OSCAL/issues/726

**Comment by butler54** [comment]
@vikas-agarwal76 - based on the exchange protocol requirements we should revisit this as an issue.
