### ISSUE TITLE
Improve error messages for validate

### ISSUE THREAD

**Issue by fsuits** [IBM/compliance-trestle#543]
Improve error msgs from validate when file has bad name in trestle directory or is loaded from outside the directory.

**Comment by fsuits** [comment]
currently if you ask it to validate an arbitrary file not in a trestle project, it says "Trestle project model not found at <path>.  This message could be clarified.  It also says this if the file is valid e.g. catalog.json

If you ask it to validate a file not in the correct directory  such as catalogs\foo.json it will try to load it and complain if it is a bogus file.  But it shouldn't even try to load it.

If the file at catalogs/catalog.json is valid - it will validate it properly.  But it isn't in a valid location.

If you put a catalog.json in profiles it will complain that it is not a profile.  But it shouldn't load it in the first place.

Validate needs to determine file path relative to trestle root first and give warning accordingly before loading the file.  And the "trestle project not found" wording needs change.

**Comment by vikas-agarwal76** [comment]
Done.
