### ISSUE TITLE
Trestle reports error as warning

### ISSUE THREAD

**Issue by deenine** [IBM/compliance-trestle#545]
**Describe the bug**
Typically a `WARNING` indicates that there was an issue, but the operation was able to complete, an `ERROR` indicates that the operation had an issue and was aborted. 

Per the [tutorial](https://ibm.github.io/compliance-trestle/tutorials/trestle_sample_workflow/#step-5-split-metadata-further-using-wildcards), this operation to split `roles.json` raises a warning which is misleading because the operation does not complete.

```
trestle.workspace/catalogs/mycatalog/catalog/metadata $trestle split -f ./roles.json -e 'roles.*'
WARNING:root:wrapper_alias is required for a collection type object
```

**To Reproduce**

1. Follow [tutorial](https://ibm.github.io/compliance-trestle/tutorials/trestle_sample_workflow) to step 5.

**Expected behavior**
`ERROR:root:wrapper_alias is required for a collection type object`

**Comment by butler54** [comment]
@fsuits can you confirm?

**Comment by fsuits** [comment]
This particular example no longer gives warning.  I am not aware of other situations where ERROR comes up when it should be WARNING so I will close this.
