### ISSUE TITLE
Provide a way for href's to redirect to models within the trestle workspace

### ISSUE THREAD

**Issue by fsuits** [IBM/compliance-trestle#557]
The href's in OSCAL files should correspond to where the files will ultimately be placed - but at the same time it would be useful for trestle to follow href's if files within the workspace are being worked on.

A simple approach would be to create a lookup table mapping href values to model types/names in the trestle workspace.  Perhaps a command like:

trestle href add catalog '../../../nist_catalog.json' nist_catalog

Then if trestle attempts to follow an href link it would first check if it is in the lut.

This may need to be linked to assemble if a certain directory structure is expected in the assembled models.

**Comment by fsuits** [comment]
This is handled by ignoring the path entirely and just using the file name - and requiring that the file has been imported with the expected filename.  It works that way for ssp authoring and I think the same would apply for other commands - although this assumes the file is local and a url shouldn't actually be followed to a remote file.  But perhaps if the file is not found locally the url could be followed.

**Comment by butler54** [comment]
Appending a slack conversation (slightly redacted) below with this issue. This relates to the caching functionality #170 #372 That was partially implemented but never adopted.

My proposal would be we revisit and revise the paths document and make a decision from there.


> Christopher Butler  12:46
> How am I mean to structure the href in your profile?
> 12:47
> for ssp-generate (doing some testing)
> 12:47
> json
>         "imports": [
>             {
>                 "href": "../../catalogs/800-53/catalog.json",
> 12:47
> does not seem to work.
> 
> Frank Suits  12:47
> it can be a uri or url and only the last bit is ignored
> 
> Christopher Butler  12:47
> what do you mean the last bit is ignored.
> 
> Frank Suits  12:48
> this is the way i decided to make them usable without changing them
> 12:48
> http://nist/blah/blah/nist-800-profile.json
> 12:48
> it knows it is a profile so it will only use the name of it in the href - i.e. nist-800-profile
> 12:49
> i think that makes sense and work ok
> 
> Christopher Butler  12:49
> So I have this
> trestle author ssp-generate -p 800-53-high -o test_ssp
> 12:50
> and in the profile (aka profiles/800-53-high/profile.json)
> 12:50
> I’m refering to a catalog
> 
> Frank Suits  12:50
> wait... one sec
> 
> Christopher Butler  12:50
> and I get this:
> trestle author ssp-generate -p 800-53-high -o test_ssp
> WARNING:root:File /Users/chris/Desktop/trestle_test/catalogs/catalog/catalog not found for load.
> 
> Frank Suits  12:51
> sorry - the catalog comes from href in the profile.
> 
> Christopher Butler  12:51
> yes
> 
> Frank Suits  12:52
> i'm looking
> 
> Christopher Butler  12:52
> But something is going funny
> 12:52
> Okay let me know.
> 
> Frank Suits  12:54
> so you import the profile with name my_prof - and with ssp-generate you use -p my_prof
> 
> Christopher Butler  12:54
> It’s finding the profile fine
> 12:54
> it’s the catalog resolution that is failing.
> 
> Frank Suits  12:54
> and what is your href in the profile?
> 12:55
> ok i see it
> 
> Christopher Butler  12:55
> ../../catalogs/800-53/catalog.json”
> 
> 
> 
> Frank Suits  12:55
> don't use catalog.json - use my_cat.json
> 
> Christopher Butler  12:55
> but it’s called catalog.json?
> 
> Frank Suits  12:56
> in other words - the .json is assumed to be something like nist-foo.json
> 
> Christopher Butler  12:56
> That is super confusing to me.
> 
> Frank Suits  12:56
> it is weird to have catalogs/catalog/catalog.json
> 
> Christopher Butler  12:56
> But it’s not
> 
> Frank Suits  12:56
> did you impmort the catalog as 'catalog'?
> 
> Christopher Butler  12:57
> it’s ./catalogs/800-53/catalog.json
> 
> Frank Suits  12:57
> oh i see
> 
> Christopher Butler  12:57
> which is the path I put it (plus the relative path that needs to change)
> 12:57
> let me zip it up
> 
> Frank Suits  12:57
> that is a proxy for .../800-53.json
> 12:57
> in a real app you would have 800-53.json
> 
> Christopher Butler  12:58
> But That’s not the file I am operating on.
> 
> Frank Suits  12:58
> and in trestle it becomes catalogs/800-53/catalog.json
> 
> Christopher Butler  12:58
> So I think if we are operating on files in the trestle workspace.. the paths need to make sense w.r.t that trestle workspace.
> 12:59
> otherwise .. I can refer to a file OUTSIDE the trestle workspace.
> 12:59
> if we give imaginary aliases.. that’s a problem in my mind.
> 
> Frank Suits  12:59
> well - i made an issue for this and i think it's a reasonable compromise.  it avoids having to change the href
> 13:00
> it is just a simple mapping of mycat.json to catalogs/mycat/catalog.json
> 13:00
> that is in effect what trestle does anyway
> 13:00
> so i propose href's get interpreted as such
> 
> Christopher Butler  13:01
> I don’t think anyone will understand that.
> 13:01
> I’ve got a variant I could propose.
> 
> Frank Suits  13:01
> well - they already have to understand that mycat.json becomes catalogs/mycat/catalog.json
> 
> Christopher Butler  13:01
> but that’s an import
> 
> Frank Suits  13:01
> but it is referred to by name as mycat
> 13:02
> so in the href - only the name matters
> 
> Christopher Butler  13:02
> Wait one second - hear me out.
> 13:02
> So my issue is you are parsing a relative path that does not exist.
> 13:03
> So a user needs to know how to translate that relative path.
> 
> Frank Suits  13:03
> i'm completely ignoring the path in the href
> 13:03
> i only extract the name
> 
> Christopher Butler  13:03
> But what I showed you was a relative path.. . hence the confusion.
> 
> Frank Suits  13:03
> normally that name would match the external name and the internal name
> 
> Christopher Butler  13:03
> So here is my proposal on what we should plan for:
> 13:05
> User has a few choices:
> 1) Provide a URI for an external document which is assumed to be a fully qualified path which works (aka you can just download it).
> 13:05
> We can explore building a better loading capability. The caching capability we should revive and use.
> 13:06
> 2) We support an href: ‘trestle://model_type/model_name’ for these relative references. That way we know it’s for trestle. User can understand it is for trestle.
> 13:07
> or 3) user provides the full relative path for trestle to the root folder.
> 13:08
> the reason why I like this is for version (2) - we can add to ‘assemble’ a piece to decode those into proper URIs.
> 13:08
> I’m happy to drop 3 btw.
> 13:09
> But the magic assuming different paths becomes really confusing to me if we are not explicit about what it is.
> 13:09
> We can test with a few foks.
> 
> Frank Suits  13:09
> I think there is a disconnect somehow.  please find the issue where I diiscuss it and enter your suggestions.
> 13:10
> it may be in review - but you can find it as authored by me
> 13:11
> in my view the href is the same one used when importing the catalog.  And ssp-gen is the only thing that needs to know this internal mapping.
> 13:11
> but yes it can be made explicit
> 13:11
> trestle:// was my first thought
> 
> Christopher Butler  13:12
> Okay I’ll comment there so we can let you rest.. My view of that is .. I don’t think we might know all of the possible combinations and that might cause us pain.
> 13:12
> I’ll add it to the issue.
> 
> Frank Suits  13:13
> well the downside is the user will need to change href or something
> 13:13
> we could also not have the user import the catalog - and do it in ssp-gen via the href
> 13:14
> or look locally and if not found go to the url.  many ways to do it.

**Comment by butler54** [comment]
# Usecase
- SSP is to be created
- They create their own profile in trestle (or it is derived from a 3rd party generic one by importing it)
- The catalog which is external reference data (such as NIST 800-53) remains external

# High level design options
- External references are not allowed, users must import into trestle. 
  - PRO:
    - Users understand whenever changes are introduced from the catalog
    - Easier for trestle to manage
  - CON:
    - Decouples from a 'single source of truth' model
    - Users are required manually update - e.g. if upstream document changes adversely they will not automatically be made aware. 



# Challenge
- The presumption is that for the exported file via 'trestle assemble' the user will then be making that directory tree available on a server somewhere
- As part of the assemble process hrefs will need to be rewritten to be 'externally' valid.
- Users get to provide a 'dist_root' (name tbd option) that can be added to the directory tree

- NOTE: Should we flatten the 'dist' output to be one directory.


"href"= "trestle://catalogs/800-53" -> file path in trestle project dist/catalogs/800-53.json 

trestle assemble --all --dist-root 'https://ibm.com/oscal'
- https://ibm.com/oscal/catalogs/800-53.json

## Current 'dist' presumption
### trestle directory 
/catalogs/foo/catalog.json
/profiles/bar/profile.json
/profiles/foo/profile.json


/dist/catalogs/foo.json
/dist/profiles/foo.json
/dist/profiles/bar.json

## Revised 'dist' model ->CHANGE REQUIRED TO TRESTLE ASSEMBLE.
### Model A - no contention - CHOSEN MODEL
/dist/foo-catalog.json
/dist/foo-profile.json
/dist/bar-profile.json
### Model B - we could get in some trouble
/dist/foo.json
/dist/bar.json

trestle://catalogs/800-53 -> 800-53-catalog.json

 
 

#Document references inside of trestle directory


## Option 1: UUID refs
"href" : "#uuid"
- Bad as we would need to load every file (potentially inducing failure)
  - Or we could store a map
  - 
## Project name style refs (as today)
catalogs/800-53/catalog.json
profiles/800-53/profile.json
"href" : "800-53.json"
- To chris confusing
- Treats the trestle project as flat, which it is not.
- Can not infer which file type which is required for profile resolution (as profile hrefs can be catalogs or profiles).
- 
## 'Trestle' path (preferred option)
trestle://catalogs/800-53
- This is only valid within the current trestle project
- All external references (even if it is within a 3rd party trestle project) are presumed to be single file object referred to by an absolute href.



# Scenarios for hrefs inside of trestle projects
1) It's a file in the current trestle project which is referred to by 'trestle://' (OKAY and can be distributed)
2) It's a relative path (NOT OKAY)
3) It's an absolute href using https://, file://, sftp:// (OKAY but must never be a single file)
4)
