### ISSUE TITLE
Improve Markdown handling in SSP authoring lifecycle

### ISSUE THREAD

**Issue by butler54** [IBM/compliance-trestle#565]
## Issue description / feature objectives
Current Markdown parsing to generate an OSCAL SSP is brittle and may be prone to silent failures. Markdown parsing capability in `MarkdownValidator` most likely needs to be broadened to deal with a wider set of circumstances (such as 'render everything below this heading level into HTML / ASCII').

With a more robust handling capability current ssp assembly can be made more robust and/or precise in terms of error handling.

## Steps to Reproduce the Problem

1.
1.
1.

## Specifications

- Version / branch:
- Platform:
- Subsystem:

**Comment by vikas-agarwal76** [comment]
No needed.
