### ISSUE TITLE
Improve/ensure consistency of command arguments, e.g. model names vs. file names

### ISSUE THREAD

**Issue by fsuits** [IBM/compliance-trestle#566]
trestle has many commands and there is increasing need for consistency of meaning across the commands, to avoid confusion in usage.

Examples guidelines are:

 -f may be an actual file name, a directory, or a model name.  Is it good to have this flexibility or is it confusing?  Should it strictly be an actual file name with extension?

-n should always be a model name - and never a file

-m is useful for markdown content - but should never be a file.  i.e. it should refer to a directory or task name

-o is useful as a clear statement of output - but sometimes that output is an actual file name and sometimes it is a model name.  So that can also be confusing.

-p specifically refers to the name of a profile model present in the trestle workspace.  Is it ok to use a single letter when the type of model needed is clear?

-y for a yaml file.  If it is intended as a yaml header, it could be -yh.  It needs to be distinct from -h.

Many of these ambiguities can be dealt with by special handling when the command is executed - e.g. to convert a file name to a pure model name - but that may end up being confusing to users.

Issue is resolved by deciding on a forward-looking path for expected command arguments and establishing guidelines for their usage.

In addition, guidelines should be set for when errors should be raised vs. resolving ambiguities in the code and figuring out what the user wants.

**Comment by fsuits** [comment]
This should be considered as part of ongoing work to create a manager for command invocations.

**Comment by vikas-agarwal76** [comment]
Done.
