### ISSUE TITLE
Make OscalBaseModel.copy_to more opportunistic

### ISSUE THREAD

**Issue by butler54** [IBM/compliance-trestle#594]
## Issue description / feature objectives
The current methodology for OSCAL.copy_to was built when trestle contained a large number of duplicate classes. This is no longer the case. Given this we want the copy_to to be more aggressive.

## Basic
Given  class A with fields b, c, and d. and class E with fields b and c allow an opportunistic copy from A to B.

## Advanced:
Given the previously mentioned class A, and class F with b,c,d, and g fields (all compulsorary) allow an update / generate style methodology to partially update F and generate the appropriate placeholders for missing content.

## Completion Criteria
-

**Comment by vikas-agarwal76** [comment]
Not planing to work on it.
