### ISSUE TITLE
Remove 3rd-party-schema-documents and embed into the website only.

### ISSUE THREAD

**Issue by butler54** [IBM/compliance-trestle#596]
## Issue description / feature objectives
`3rd-party-schema-documents` currently is not required as we have no external json schema objects we are depending on. Remove the documentation from this folder and embed into the website / (aka docs) folder such that there is only one copy of the documentation.

## Completion Criteria
- [] Content in `3rd-party-schema-documents/IBM_assessment_result_interchange_SCC` is migrated to the `docs/` folder an available on the website.
-

**Comment by butler54** [comment]
Can  someone please clean out the directory now this is all setup?

**Comment by jayhawk87** [comment]
@butler54 - is this completed? I don't see a `3rd-party-schema-documents` in the GH tree at this point...

**Comment by vikas-agarwal76** [comment]
it seems the folder has been removed.
