### ISSUE TITLE
Accommodate partial OSCAL documents in trestle workspace

### ISSUE THREAD

**Issue by degenaro** [IBM/compliance-trestle#605]
## Issue description / feature objectives

`trestle import` and `trestle validate` should accommodate partial OSCAL documents. For example, a partial SAR document may be comprised of just the `results` subtree. This would allow for `tanium-to-oscal` and `osco-to-oscal` transformer produced documents to be validly stored in trestle workspace.

The ability to permit partials during import and validate could be controlled with a flag, such as `--partials-permitted`.

![image](https://user-images.githubusercontent.com/520029/123958410-056a7600-d97b-11eb-9c04-93225543107a.png)

## Completion Criteria

`trestle import ` and `trestle validate` permit partial OSCAL documents.

**Comment by butler54** [comment]
With the underlying pydantic models this his highly problematic when run w.r.t the existing commands.

I can see a few solutions:
1) task does dump code into the appropriate location and uses generators to insert the minimum necessary 'replace me' content as appropriate (not elegant, however, it works)

2) Any partial objects are put *outside* the schema objects
-  If this is the case we would need some form of custom object validation (e.g. which does not presume trestle directory structures).
- `trestle schema-validate -e 'element path' -f ./file.json
