### ISSUE TITLE
Model generation as part of the CICD build process.

### ISSUE THREAD

**Issue by butler54** [IBM/compliance-trestle#61]
## Issue description / feature objectives
One of the original thoughts on trestle is to automate the build process for keeping up to date with oscal as the standard evolves. 

One concern I have is that our 'drift' today is inconsistent. We have not made a firm decision on 'which' version of OSCAL we use (apart from the latest) - and differences are mainly driven by when we decide that we need to mess with the OSCAL models.

I can see one a few approaches could be taken.

We change our generation script to look for a release explicitly: https://github.com/usnistgov/OSCAL/releases.
The laziest way is we do this manually in a 'set and forget' mode, however, that may expose us to drift.

A second approach could be to put a check in the CICD pipeline that we are always using the 'latest' version of oscal. This could be defined one of two ways.
1. The latest tag / release
1. The latest in trunk

Given the way OSCAL are managing their repo it's possible to converge both options so latest in trunk will be the latest tag (as they have working and release directories in the repo.).

Once we have a decision here - the next question is on how to deploy it. My gut feel would be the best way to check would be to run the 'update' code in the CICD pipeline and fail the check if it produces a change. That way the user would need to do and update locally before a PR could be merged.

## Completion Criteria
- Strategy decided and documented in contributing.md
- CICD / other changes are implemented.

**Comment by butler54** [comment]
@fsuits - Given where we are I wonder if this is possible? Asking it another way.. if I run make gen_oscal will it produce the same files consistently?

**Comment by fsuits** [comment]
As long as the NIST schemas don't change I believe the output files will be unchanged.  So I don't see why make gen-oscal can't be part of the CICD process.  It will just add some time.

**Comment by butler54** [comment]
@fsuits we might want to look at this again. If your class generation is now deterministic I think we can do a 'check' which automatically generates this and alerts us if there is a change. 

What I would not propose doing is allowing this to do a 'git submodule remote merge' (aka pulling the latest), but just a `git submodule update --init`. This will at least ensure that the code is in line with the current version of OSCAL tagged in the repo.

If you are confident that your code is deterministic - I can introduce the PR.

**Comment by fsuits** [comment]
I think this is all fine with one caveat that updates to datamodel-codegen may cause a change in the generated python even with the schemas being the same - but that is ok.  It doesn't take long to generate the classes so there isn't much overhead.  If somehow there is still something non-deterministic I expect I can find it easily - but with each file having its classes sorted prior to ordering optimally I don't know what would be non-deterministic.

**Comment by butler54** [comment]
This has been in the pipeline for a while and with the change in operating model of NIST I would suggest we close in favour of #614.

**Comment by butler54** [comment]
Based on discussion - we will attempt this first. #614 to be closed.

**Comment by butler54** [comment]
Close as this would block us if a destructive change occurred, it would block us completely.
