### ISSUE TITLE
Ensure reasonable content in ssp response text is allowed

### ISSUE THREAD

**Issue by fsuits** [IBM/compliance-trestle#616]
The full scope of content (headings, bolds, etc) in response text for ssp-assemble should be formalized, but at the least there should be allowed multiple paragraphs of prose.

Confirm that multiple paragraphs and reasonable prose is handled properly during ssp-assemble.

**Comment by fsuits** [comment]
This has been implemented in the sense that all the text in the response field is pulled into the json ssp.  So I think this can be closed and issue #621  can take over in terms of determining what should and should not be allowed.

**Comment by butler54** [comment]
The one question I have is whether json control characters (e.g. `"`) are escaped properly
