### ISSUE TITLE
Determine what is and is not allowed in response text, e.g. formatting, tables, headings, etc., during ssp assemble

### ISSUE THREAD

**Issue by fsuits** [IBM/compliance-trestle#619]
Currently ssp assemble copies all text as the response for each statement part in the human-edited control markdown content.  This allows raw text, markdown, html to be captured in the assembled json file.

As a developer I need to know what the user expects to be able to store in the json, and how rigidly I should enforce a given overall structure - e.g. are they allowed to insert headings of any kind, or just headings below ###, which currently used for each Part where the user enters response prose.

If violation of the content is found, I propose reporting the error and aborting the assemble task.

**Comment by butler54** [comment]
Isn't this a duplicate of #616

**Comment by butler54** [comment]
https://pages.nist.gov/OSCAL/reference/datatypes/#markup-data-types <-- Markup multi line is allowed. I'm not sure what our decision would be around html vs markdown.
