### ISSUE TITLE
Split does not work properly if a directory path is specified in -f

### ISSUE THREAD

**Issue by vikas-agarwal76** [IBM/compliance-trestle#630]
**Describe the bug**
Split does not work properly if a directory path is specified in -f. 
For example, if the command is issued from <model-dir> directory 
trestle split -f 'catalog/metadata.json' -e 'metadata.props' 
it will create -
<model-dir>/catalog/catalog/metadata.json and
<model-dir>/catalog/metadata/props.json

The metadata.json should be in <model-dir>/catalog/ and not <model-dir>/catalog/catalog/ directory.

if the directory is first changed to <mode-dir>/catalog and then the command is issued -
trestle split -f 'catalog/metadata.json' -e 'metadata.props'
then it works properly.

**Comment by butler54** [comment]
Confirmed to not be a problem anymore.
