### ISSUE TITLE
Improve type consistency across the board for trestle.

### ISSUE THREAD

**Issue by butler54** [IBM/compliance-trestle#640]
## Issue description / feature objectives
This is really a meta issue for the backlog of task that need to be performed.  The current state of type validations (excluding autogenerated code) is pretty mixed. As normal with python some typing is not easy.

Note: I've noticed that handling 'by exception' rather than optional variable is easier. 

## Completion Criteria
- [ ] All trestle files are covered
- [ ] Alltest files are covered
- [ ] Mypy passes (at least at a basic level) in CICD
- [ ] Documentation for developers updated
- [ ] Type annotations by mypy enforced in pipeline.

Note: It might be possible to stage this by adjusting the 'strictness' of mypy.

**Comment by vikas-agarwal76** [comment]
Almost done.
