### ISSUE TITLE
As a trestle user I would like a simple API to do schema validation of OSCAL objects

### ISSUE THREAD

**Issue by butler54** [IBM/compliance-trestle#647]
## Issue description / feature objectives
Unfortunately not everyone will buy into the trestle directory structure - for example they are implementing a service in golang and have to build an OSCAL api.

trestle can still help validate objects - particularly partial objects of the schema.

Assumptions:
1) Single files only - no distributed files
2) Json / yaml files
3) Does not have to be in a trestle root directory
4) Extra validations are not implied by default.

Form of the command
trestle schema-validate -f object.yaml -e 'element path' --no-validators 

No validators disables the 'default' set of validators that run in addition to the json schema.

Specific validators such as fedramp will be dealt with in the future.

**Comment by fsuits** [comment]
I guess the types of validation are:

- valid json or yaml
- valid oscal schema - i.e. no pydantic complaints
- known higher level restrictions such as no duplicate uuid's
- known narrower restrictions such as FedRamp's restricted schema

So it would be good to clarify what is needed to validate in the short term - and provide extensible path forward if there is likely to be need for specialized validators.  The existing validator factory should be fine for any model that can be loaded in memory, but a general way to validate as part of the loading process would be good.

**Comment by butler54** [comment]
So I think there is 3 tiers:
1) Schema
2) validators beyond the json schema
3) Specific ones not everyone needs like fedramp

For this initial usecase I think we can consider (1) and (2) I think the challenge will be dealing with (3) when it comes up as this is effectively something we have to select.

I've updated the initial post above with some thoughts
