### ISSUE TITLE
As a multi-environment system owner I want support to work with unidirectional security barriers in trestle.

### ISSUE THREAD

**Issue by butler54** [IBM/compliance-trestle#658]
## Issue description / feature objectives
Suppose we have two systems A and B, where one system (A) is more generally accessible (within and without a service provide) and system B is highly restricted. 

System (A) and system (B) are based on the same architecture, however, may have significant differences

e.g. Deployment topology, Services available, and some process and procedures.

E.g. we need to do a 'merge' update across repositories.  Where B pulls in content from A but not reverse. This may be possible using git based workflows only (and could be documented that way).

**Comment by vikas-agarwal76** [comment]
This can be defined by git workflows and appropriate access. Similar to separate repositories for catalog, profile, ssp and updates from one repo being pushed to other.
