### ISSUE TITLE
Refactor get_inner_type specifically type annotations.

### ISSUE THREAD

**Issue by butler54** [IBM/compliance-trestle#672]
Type annotations are currently incorrect as trestle deals with OBM and the associated output.

## Issue description / feature objectives
I'm not sure we are going to get a fantastic set of type annotations that make sense without some refactoring. The core challenge is where do we deal with the transition between pydantic __root__ structures and other measures.

**Comment by vikas-agarwal76** [comment]
We worked on some aspects of it. Not clear what else needs to be done.
