### ISSUE TITLE
Support exposing location of parameter substitutions in the ssp / profile workflows.

### ISSUE THREAD

**Issue by butler54** [IBM/compliance-trestle#696]
## Issue description / feature objectives
WIth default values it can be unclear where parameters need to be set within the profile. Currently we resolve and substitute the parameters into a control prose in the markdown documents.

Produce a flag to enable or disable parameter substitution into printed control prose in the text.  Users will need to visit the underlying oscal model to set the parameters (ideally in the profile).

**Comment by butler54** [comment]
This is a not right now.

**Comment by vikas-agarwal76** [comment]
This is not relevant now. We capture the actual / default value separately.
