### ISSUE TITLE
merge fails in workflow tutorial step 5 after split of roles and resp. parties

### ISSUE THREAD

**Issue by fsuits** [IBM/compliance-trestle#719]
## Describe the bug

merge is failing to merge `roles.*` or `responsible-parties.*` after split

## To Reproduce

In the workflow tutorial step 5 the following steps are taken:

1. `cd metadata`
1. `trestle split -f ./roles.json -e 'roles.*'`
1. `trestle split -f ./responsible-parties.json -e 'responsible-parties.*'`

This all works as intended, but the reversal step fails:

1. `trestle merge -e 'roles.*,responsible-parties.*'`

The error is: `WARNING:root:'roles.json' is not in the subpath of 'C:\\tmp\\test2' OR one path is relative and the other is absolute.`

This warning also happens if you do either `roles.*` or `responsible-parties.*` individually.

## Expected behavior

It should have reversed the split

## Environment

- OS: Windows, but I don't think it is a windows issue

**Comment by butler54** [comment]
I cannot reproduce this on a mac at this stage. I can try in a windows VM as required. 

The following command chain (that should work across platforms worked for me. If you can test with this on windows please let me know if you have issues.
```
rm -rf test_trestle
mkdir test_trestle
cd test_trestle
trestle init
trestle import -f REPLACE_ME/NIST_SP-800-53_rev5_catalog.json -o mycatalog
cd catalogs/mycatalog
trestle split -f ./catalog.json -e 'catalog.metadata,catalog.groups,catalog.back-matter'

trestle merge -e 'catalog.metadata,catalog.groups,catalog.back-matter'
trestle merge -e 'catalog.*'
trestle split -f ./catalog.json -e 'catalog.metadata,catalog.groups,catalog.back-matter'
trestle merge -e 'catalog.*'
trestle split -f ./catalog.json -e 'catalog.metadata,catalog.groups,catalog.back-matter'
cd catalog
trestle split -f ./metadata.json -e 'metadata.roles,metadata.parties,metadata.responsible-parties'
cd metadata
trestle split -f ./roles.json -e 'roles.*'
trestle split -f ./responsible-parties.json -e 'responsible-parties.*'
trestle merge -e 'roles.*,responsible-parties.*'
```
