### ISSUE TITLE
trestle validate fails on split files probably due to load_distribute

### ISSUE THREAD

**Issue by fsuits** [IBM/compliance-trestle#720]
## Describe the bug

When controls are split off from a catalog, the catalog fails validation with:
`WARNING:root:1 validation error for Catalog
controls
  extra fields not permitted (type=value_error.extra)`

## To Reproduce

1. Create a catalog with controls
1. Split off the controls
1. Validate the now split catalog
1. Validate does a load_distributed so this should be fine but it give the above error

## Expected behavior

Validation always uses load_distributed so it should make no difference if the file is split or not.

## Environment

- OS: Windows but I doubt that's a factor

**Comment by butler54** [comment]
Can you please provide the set of commands (including any cd's performed) when running this command?
