### ISSUE TITLE
`trestle create` & `trestle add` suggested interfaces changes.

### ISSUE THREAD

**Issue by butler54** [IBM/compliance-trestle#721]
## Issue description / feature objectives
TO BE REVIEWED WITH MULTIPLE STAKEHOLDERS FIRST
Trestle contains two functions that allow the user to increase the amount of OSCAL content.

`trestle create` will instanciate a new top level oscal model e.g. Catalog / Profile etc.

`trestle add - will instanciate a new (using a generator) oscal object which is injected into an existing top level object (e..g it will add a control to a catalog).

There has been some confusion as `add` is percieved to `add` an 'existing' model into the current catalog control etc.

In order to make this clearer the following change is suggested

`trestle create` becomes `trestle new` e.g. `trestle new catalog -o my_catalog`

and `trestle add` becomes `trestle create` e.g.  `trestle create -e `catalog.controls.control` -f ./my_catalog/catalog.json would create the catalog.controls.control object.

## Caveats / Assumptions
This is a breaking change we are still assuming a beta environment for this.

## Completion Criteria
- [ ] Commands updated *AND* file / test names remapped to match.
- [ ] Documentation updates
- [ ] Updates of repository api
- [ ] All examples in https://github.com/IBM/compliance-trestle-demos reviewed for changes.

**Comment by fsuits** [comment]
My perspective:

I think there is a big distinction between creating something completely new, like a catalog and its directory, vs. creating something new within something existing - e.g. a control in an existing catalog.

So to me, create does match what I expect create to do, when it comes to a catalog - and new doesn't fit as well.

I would use create for top level models - that do not exist at all yet - and clarify it for creating something new within an existing model.

create catalog -o my_cat

create --within -f catalog.json -e catalog.controls.control

or simply

create --within catalog.json -e catalog.controls.control

A separate issue is whether the 'add' acts on a file or a model (that may have been split).  If you split all controls from a catalog  then there is no controls.json file to operate on or 'add to'.   Does the -f always refer to the top level model .json file?  Could it be something like:

create --within catalog/my_cat -e catalog.controls.control

**Comment by fsuits** [comment]
Another approach is simply:

create catalog -o my_cat

create element -f catalog.json -e catalog.controls.control

Both operations create something from nothing.  The first has no source file so you know it is created from scratch.  The second has a source file and it's clear an element is being created within it.  You could also drop the 'element' and just do:

create -f catalog.json -e catalog.controls.control

**Comment by degenaro** [comment]
I kind of like this, similar to database CRUD, we are creating something in
the trestle workspace.

**Comment by butler54** [comment]
I like the second approach as it's an easy switch to code in. @fsuits i'll put this on your backlog and we can re-assess based on need.
