### ISSUE TITLE
Fix merge command `trestle/core/commands/merge.py` inconsistent behaviour

### ISSUE THREAD

**Issue by enikonovad** [IBM/compliance-trestle#747]
## Describe the bug

When using `Trestle` library, installed via `pip`, the `merge` command fails to merge the broken down catalog file after the folder is opened by the user. Opening the folder with broken down catalog leaves the merge command in permanent state where the merge of the earlier separated file is no longer possible and the following error is thrown:

`trestle.core.commands.merge:72 ERROR: Merge failed: Invalid file content type FileContentType.DIRLIKE`

## To Reproduce

Steps to reproduce the behavior (on MacOS):

1. Go to the [tutorial page](https://ibm.github.io/compliance-trestle/tutorials/trestle_sample_workflow/)
2. Complete steps 1 and 2 in a terminal
3. Split the catalog as described in step 3
4. Go to the catalog folder in the Finder
5. Open created after split folder `catalog`
6. Return to the terminal, now try to merge the file as described in step 3
7. Observe the error: `trestle.core.commands.merge:72 ERROR: Merge failed: Invalid file content type FileContentType.DIRLIKE`

## Expected behavior

Opening the folder by the user does not affect the merge command and the file could be merged back.

## Environment

- OS: macOS Big Sur 11.6
- Python version: 3.9.7
- Trestle version: v0.24.0

**Comment by butler54** [comment]
Identified as .DS_Store files on mac os can be indexed within the directory tree. 

Suggested fix is to use fs.is_hidden within merge / load distributed code to ensure hidden files are ignored.

**Comment by butler54** [comment]
Most likely in load distributed where Path.iterdir() is called.
