### ISSUE TITLE
trestle author {docs| headers | folders} to allow multiple template versions.

### ISSUE THREAD

**Issue by butler54** [IBM/compliance-trestle#761]
## Issue description / feature objectives
As template enforcer I would like to be able to allow multiple templates within the repository.
In that approach the trestle repositories would be (ideally in a backwards compatible way) redesigned such that there is 'fail over' that is allowed in terms of the templates.

## Caveats / Assumptions
- template versions follow semantic versioning to determine the latest
- 

### Simple
- Templates will either be associated via descending the available semantic versions of the template
- If a template is not a match the latest is always used for reporting errors.
- A strict flag exists to measure against the latest.

## Proposed template structure.
Currently the templates are structured in a way such that:
```
root_folder/.trestle/author/{template_name}/{template_objects}
```
e.g.
for governed docs on a folder called 'ADPs' it would be

```
root_folder/.trestle/author/ADPS/template.md
ADPs/instance_1.md
ADPs/instance_2.md
```
The proposal would be that for backwards compatibility two layouts would be detected:
- The existing structure
```
root_folder/.trestle/author/ADPS/template.md
```
- A new structure which is labeled by a folder(s) which are semantically versioned
```
root_folder/.trestle/author/ADPS/0.0.1/template.md
root_folder/.trestle/author/ADPS/0.0.2/template.md
root_folder/.trestle/author/ADPS/0.1.0/template.md
root_folder/.trestle/author/ADPS/1.0.0/template.md
```
Note that both models can not co-exist.

## Changes that are required
- For each of the operating models a method is required to detect which 'mode' (e.g. version or single version) is used.
   - This will be most complex for 'governed folders' where folders already have meaning. The net result being that semantically versioned folders will be prohibited, unless describing template versions
- Update execution to allow 'fail over' based on the semantic version label.
- Add a '--latest' flag which only allows the latest version, if multiple versions are provided.
- Update testing and documentation.

**Comment by jayhawk87** [comment]
@butler54 - after some more thought and some TDD, I've edited my above comment to flesh out what I'm thinking in more detail ...
