### ISSUE TITLE
Clean up 'critical' code smells from sonarcloud

### ISSUE THREAD

**Issue by butler54** [IBM/compliance-trestle#779]
## Issue description / feature objectives
Now we have deployed sonarcloud there remains the issue of what to do with legacy 'CODE SMELLS'. 

With the current volume my expectation would be that we target the critical code smells as a background activity to gradually clean up the code base:

https://sonarcloud.io/project/issues?id=compliance-trestle&resolved=false&severities=CRITICAL&types=CODE_SMELL

## Caveats / Assumptions
- Everyone hacks away at this slowly when the have time
## Completion Criteria
- No of 'critical' code smells is < 5.

**Comment by degenaro** [comment]
FYI: [CognitiveComplexity (1).pdf](https://github.com/IBM/compliance-trestle/files/7329819/CognitiveComplexity.1.pdf)

**Comment by vikas-agarwal76** [comment]
Done
