### ISSUE TITLE
As a developer I would like to use MarkdownAPI for all markdown related tasks

### ISSUE THREAD

**Issue by enikonovad** [IBM/compliance-trestle#802]
## Issue description / feature objectives
As of now reading of edited markdown controls is still partially done via `ControlIOReader` class. It would be nice to move that logic to the `MarkdownAPI` for consistency.

Additionally the markdown writing functionality can also be moved to that API.

## Completion Criteria
- All markdown-related reading operations are done via `MarkdownAPI` class.
- Edited markdown controls are read using `MarkdownAPI`.
- Nice to have: markdown-related writing operations are also done via `MarkdownAPI`

**Comment by vikas-agarwal76** [comment]
not worth it. Lot of refactoring.
