### ISSUE TITLE
As a developer I would like consistent and concise loading and saving of top level model files

### ISSUE THREAD

**Issue by fsuits** [IBM/compliance-trestle#810]
## Issue description / feature objectives

There are many times in core code and in tests that models need to be loaded by type and name.  In the past this involved on the fly generation of the needed file path and other overhead.  A new repository class has been introduced mainly for use outside of the core trestle code, but in additon, new methods direct loading and saving of top level models have been introduced.  These methods should be used wherever possible.

## Caveats / Assumptions

Existing ad hoc code to access models should be replaced by the new methods and developers should be aware these functions exist.  If more elaborate and repeated interaction with a model is needed, the Repository or ManagedOSCAL classes should be considered.

## Completion Criteria

All loading, saving and path manipulation of top level models use the new "top_level_model" functions in fs.py, and developers are aware of them.

**Comment by vikas-agarwal76** [comment]
done
