### ISSUE TITLE
Proposed framework for oscal to oscal transformations

### ISSUE THREAD

**Issue by butler54** [IBM/compliance-trestle#811]
## Issue description / feature objectives
Trestle tasks have been construed for unique tasks which may include a large number of parameters related to content that is external. The complexity of this has relied on a configuration file approach to perform various transformations.

When we consider OSCAL files **exclusively** the complexity is more limited and may be containable to a relatively straight forward command.

The objective here would be (as far as is practical) allow chaining of the transformations. Under this the suggestion is of the form:
trestle transform {input top level model type} --input {potentially multiple instances} --output {single output model} --transform x --transform y --transform {order of operations specified by order provided} --extra-params.

Under this regime all parameters required for the transforms would be globally scoped across all transforms (e.g. if a profile is provided it is consistently used). This will limit the depth of transform that is executable, however should contain the complexity.

### A note on files authored using trestle author in markdown
- This issue presumes that users of this functionality must first convert the markdown to oscal then run the transformation tasks.
- It may be possible to cross link this functionality as well.

## Transforms 
Plase note names are indicative
### filter-by-profile:
- Filters the input document by the controls / parts of a corresponding resolved profile
- Applies too (in decreasing order of priority:
  - SSP
  - Component Def
  - AP
  - AR 
  - POAM
- Is a 1:1 map of the same type for input to output
  - Required a `--profile` to be passed

### filter-exclude-components
- Removes components specified by a --components argument and returns the same object to the output location
- Applies to:
   - Component definition
   - SSP
   - AP
   - AR
   - POAM
### filter-include-components
- Filters exclusively for components specified by a --components argument and returns the same object to the output location
- Applies to:
   - Component definition
   - SSP
   - AP
   - AR
   - POAM

### jijna
Applies to all documents where the document model is processed through a jinja engine. It presumes that the context for templates is the trestle root directory and users can pass:
- Input `include` files
- binary vars that will be true when passed e.g `--jinja-var=foo`
- A limited set of pre-built jinja vars that can be extrapolated and documented (e.g. current time)
- Requires special handling of OSCAL parameter substitutions

### aggregate
- many to one aggregation of a given document type with precedence

### resolve profile
- Runs the profile resolution process
-  input is one profile 
- output is one catalog

#### component-defintion-to-ssp
- Best effort conversion from a component definition to a ssp
#### ssp-to-ap
Best effort conversion of a ssp to an ap

#### ap-ar
Best effort conversion of an ap to an ar.

#### cd-profile
Use the component definition to configure a 'all controls used and configured' profile

#### ssp -> component definition
Convert a ssp to a vendor statement (potentially with property based filter)

## Caveats / Assumptions
- Transformations are exclusively based on the assumption we are handling a top level object.
- 
- One to many transforms are not supported, run mulitple workflows.
- if mutliple inputs are provided an aggregation operation is required

**Comment by fsuits** [comment]
# Transform operations and arguments
| type | input | transform | output | header | filter-by | regenerate | sections | 
| ----- | ----- | ----------- | -------- | -------- | -------- | ------------ | --------- | 
| profile | my_prof_json | generate | my_prof_cat_md | my_header | | | sec1,sec2|
| ssp | my_prof_cat_md | assemble | my_ssp_json | | comp1,comp2  | x | |
| catalog | my_cat_json | generate | my_cat_md | my_header |
| catalog | my_cat_md | assemble | my_cat_json | | | x |
| ssp | my_ssp_json | filter | my_filtered_ssp_json | | my_prof_json|
