### ISSUE TITLE
Allow recursive groups in profile resolution.

### ISSUE THREAD

**Issue by butler54** [IBM/compliance-trestle#829]
## Issue description / feature objectives
Currently when conducting merges only one level of groups exist. It is possible multiple levels exist, which will be lost / overwritten in a merge.

Refactor existing methods to handle multiple levels of groups.

Note: Currently `Merge._merge_lists` presumes the lists are of controls. If we articulate a common requirement where the list item requires an `id` attribute this function should be generalizable.

**Comment by fsuits** [comment]
This is now supported by ProfileResolver and group structure is preserved, including groups containing groups.
