### ISSUE TITLE
Refine profile handling of `props` modify statements.

### ISSUE THREAD

**Issue by butler54** [IBM/compliance-trestle#830]
## Issue description / feature objectives
Current version of profile resolution currently only acts within of exactly the control id provided (e.g. nested controls should be explicitly addressed).

- In order to refine the profile resolver we need to understand whether scope is explicitly limited to a control or expands to nested controls as well (see: https://github.com/GSA/fedramp-automation/issues/188) as well as OSCAL gitter.

**Comment by fsuits** [comment]
As I understand it, NIST intends to confine the scope to the control so we do not need to check nested controls.  If this is true we should close this.

**Comment by butler54** [comment]
Agreed.
