### ISSUE TITLE
Ensure that `include-all` is explicitly handled in profile resolution 

### ISSUE THREAD

**Issue by butler54** [IBM/compliance-trestle#834]
## Issue description / feature objectives
Currently it is only handled by 'if a user does not list controls - add all controls'. This could lead to situations where the effective XOR requirement (you can have a list of controls or include-all; but not both or neither), is not met.

**Comment by fsuits** [comment]
This is now handled in ProfileResolver.

**Comment by fsuits** [comment]
@butler54 please review and close
