### ISSUE TITLE
As a trestle developer or SDK user I am puzzled by oscal classes that seem common but aren't

### ISSUE THREAD

**Issue by fsuits** [IBM/compliance-trestle#850]
## Describe the bug

This isn't really a bug but something that needs to be documented.  OSCAL classes are placed in common if more than one model file refers to them in exactly the same way.  But two models that appear to be the same may be different because they depend on classes with the same name but ultimately have a different class that is referenced by the same name.

## To Reproduce

The Step() class appears identically in assessment_results, assessment_plans, and poam - and the one non-common class it references is ReviewedControls - but even that class is identical in all three files.  And it references ControlSelection - which is also identical.  But finally, ControlSelection references SelectControlById - and there is a distinct version of that class in profile.

Because of that linked reference to something that is not truly common, all classes involved need to be non-common and duplicated in the various files.

## Expected behavior

This is already working correctly.

**Comment by butler54** [comment]
Okay makse sense.
