### ISSUE TITLE
Allow all trestle author *-assemble commands to do an 'in place update' so that uuids / other data is not changed.

### ISSUE THREAD

**Issue by butler54** [IBM/compliance-trestle#854]

**Comment by fsuits** [comment]
@butler54 Addressing issue #820 also, I propose the following generic transform command with the following structure:

`trestle transform --type [catalog|profile|ssp] --input [model or markdown name] --transform [assemble|generate|filter] --filter-by [model name (type is deduced)] --regenerate  --output [model or markdown name]`

The in-place-update would be handled by --regenerate, which has the same meaning for Import.

Assemble takes markdown to json, Generate takes json to markdown, and filter takes either one to itself.

Currently the only filter operation is to filter an ssp by profile.  Are others possible?  The assumption is that the model type needed for the filter can be inferred and only its name is needed.

- Are other transform types possible
- Are other filter types known now?
- Does this satisfy the needs going forward?
- Should this be an author sub-command?
- Should we instead stick to something special just for oscal to oscal?

**Comment by fsuits** [comment]
# Transform operations and arguments
| type | input | transform | output | header | filter-by | regenerate | sections | 
| ----- | ----- | ----------- | -------- | -------- | -------- | ------------ | --------- | 
| profile | my_prof_json | generate | my_prof_cat_md | my_header | | | sec1,sec2|
| ssp | my_prof_cat_md | assemble | my_ssp_json | | comp1,comp2  | x | |
| catalog | my_cat_json | generate | my_cat_md | my_header |
| catalog | my_cat_md | assemble | my_cat_json | | | x |
| ssp | my_ssp_json | filter | my_filtered_ssp_json | | my_prof_json|
