### ISSUE TITLE
Create a custom jinja tag to insert a specific markdown content header.

### ISSUE THREAD

**Issue by butler54** [IBM/compliance-trestle#883]
## Issue description / feature objectives
Potential resources: 
- https://github.com/dldevinc/jinja2-simple-tags
- https://michaelabrahamsen.com/posts/jinja2-custom-template-tags/

Potential form:
`{% markdown_include 'file_name.md',  'header tag' %}`

**Comment by Qiwen-Yu** [comment]
@butler54 Can I take this one, thanks!

**Comment by butler54** [comment]
@Qiwen-Yu I missed your message. We've made some progress on this here: https://github.com/IBM/compliance-trestle/tree/chore/moustache_tests

We've got extra functionality we need to implement. If you have time still please reach problem

**Comment by Qiwen-Yu** [comment]
Thank you for your feedback.

**Comment by vikas-agarwal76** [comment]
Currently we don't a need for this functionality. If required a new issue will be created.
