### ISSUE TITLE
Alter directory structure created by trestle init to include an 'other' directory structure

### ISSUE THREAD

**Issue by butler54** [IBM/compliance-trestle#89]
## Issue description / feature objectives
In discussions with the TCE team  I think we are missing a key piece for trestle init which is a 'other' directory in the project root. Previously we had discussed whether or not this is required. My hypothesis today is that we do need a directory to capture 3rd party content (such as mapping objects).

suggestion `other` or `3rd-party`  

## Completion Criteria
- [ ] Trestle spec updated
- [ ] trestle init updated.

**Comment by brunomarq** [comment]
As discussed, until we have a clear understanding of how plugins will be integrated to trestle, there is not much need for trestle to create any other folder that it is not interested in such as:
```
.trestle
dist
catalogs
profiles
target-definitions
...
```
