### ISSUE TITLE
Investigate if usage of `simulate()` is needed and if not remove it

### ISSUE THREAD

**Issue by enikonovad** [IBM/compliance-trestle#906]
## Issue description / feature objectives
Currently some commands simulate their execution prior to actually executing some operation. Removing the simulation will improve performance of those commands as the command will only need to execute operations once. 

However, careful investigation needs to be done prior of removing `simulate()` as some legacy code can depend on it.

## Caveats / Assumptions
- remove `simulate()` if it does not bring any benefit to the commands.

## Completion Criteria
- all unnecessary calls of `simulate()` are removed
- overall logic and behaviour of the commands is preserved

**Comment by butler54** [comment]
Related to:
#118, #145, #209, #214, #243

If we remove simulate many of these can be closed.

**Comment by butler54** [comment]
Also related to #463, however, I do not htihk it fully closes it.
