### ISSUE TITLE
As a OSCAL document maintainer I want a method for trestle to manage releases

### ISSUE THREAD

**Issue by butler54** [IBM/compliance-trestle#91]
## Issue description / feature objectives
This will need some further thought, however, might be interesting.

As semantic versioning  / auto releasing has been implemented within compliance-trestle i had the following thoughts.

1) Could we either automatically generate a 'dist' artifact in a way which is devops friendly
2) Could we have a command that dry-run's assemble to check whether a PR has been prepped for distribution. This would assist with the oscal packaging.
(1) and (2) above should be relatively simple once trestle assemble is provided. Additional capabilities will start to increase the functionality required to integrate into VCS platforms like github. Such as
3) On a release / tagging similar to semantic versioning the OSCAL version number may get incremented (in a fashion to be determined)
4) Release packages of documents my be assembled.

## Completion Criteria
- Behaviour here is open.

**Comment by vikas-agarwal76** [comment]
Done.
