### ISSUE TITLE
Normalization of approach of json vs yaml within the codebase.

### ISSUE THREAD

**Issue by butler54** [IBM/compliance-trestle#912]
## Issue description / feature objectives
Core components of trestle's models support both json and yaml. However, there are significant portions of both the code and documentation that are biased towards json.

### Suggested improvements
- For all documents where there is choice of *output*, where an extension is not required as part of the arguments currently, 
   - There is a config file preference for yaml vs json
   - This can be overridden by a *consistent* argument (e.g. `--extension`)
   - For a fractional oscal object, --extension MAY be used to overwrite the extension, however, the default behaviour is to be consistent with the top level oscal object.

## Caveats / Assumptions
- This is focused on the core OSCAL models and does not apply to yaml headers
-

**Comment by vikas-agarwal76** [comment]
Change documentation to say the default format s json. Yaml is supported best-effort, don't mix two formats in one mode,l and remove all references to config file in documentation.

Update init command to not create config.ini file.

**Comment by vikas-agarwal76** [comment]
Remaining: Update init command to not create config.ini file.

**Comment by vikas-agarwal76** [comment]
config.ini file is required for plugins. It existence is checked at multiple places (used for tasks), hence it has to be present, even though it can be empty. There are some name value pairs being populated during init in config file as of now which are not used. This needs to be cleaned up.
