### ISSUE TITLE
trestle transformation tasks naming convention

### ISSUE THREAD

**Issue by degenaro** [IBM/compliance-trestle#930]
## Issue description / feature objectives

The trestle transformation task naming can be better regularized. The format should be oscal-to-\<name-of-item\> or \<name-of-item\>-to-oscal. The revised list is as follows:

- tanium-result-to-oscal
- ocp4cis-catalog-to-oscal
- ocp4cis-component-to-oscal
- oscal-to-osco-profile
- osco-result-to-oscal
- ibmcis-catalog-to-oscal
- ibmcis-component-to-oscal

**Comment by vikas-agarwal76** [comment]
oscal-to-osco-profile should prob be oscal-profile-to-osco

**Comment by vikas-agarwal76** [comment]
first component is input format
second component is data type - result / catalog / profile, etc.
third component is output format

**Comment by vikas-agarwal76** [comment]
old one to update - xlsx-component-to-oscal
new one to add - xlsx-catalog-to-oscal

**Comment by degenaro** [comment]
The `final` standardized names.
<table>
<tr>
<th>original
<th>standardized
<tr>
<td>tanium-to-oscal 
<td>tanium-result-to-oscal-ar
<tr>
<td>osco-to-oscal
<td>osco-result-to-oscal-ar
<tr>
<td>profile-to-osco
<td>oscal-profile-to-osco-profile
<tr>
<td>cis-to-catalog
<td>ocp4-cis-profile-to-oscal-catalog
<tr>
<td>cis-to-component-definition 
<td>ocp4-cis-profile-to-oscal-cd
<tr>
<td>xlsx-to-oscal-catalog
<td>xlsx-to-oscal-catalog
<tr>
<td>xlsx-to-oscal-component-definition
<td>xlsx-to-oscal-cd
</table>

**Comment by degenaro** [comment]
Fixed by #1074
