### ISSUE TITLE
user-entered markdown is sometimes overridden when running `ssp-generate`

### ISSUE THREAD

**Issue by cantsin** [IBM/compliance-trestle#933]
## Describe the bug

In the [ssp generate documentation](https://ibm.github.io/compliance-trestle/tutorials/ssp_profile_catalog_authoring/ssp_profile_catalog_authoring/#trestle-author-ssp-generate-and-trestle-author-ssp-assemble) we see this paragraph:

```
If you edit the control markdown files you may run ssp-generate again and your edits will not be overwritten. When writing out the markdown for a control, any existing markdown for that control will be read and the response text for each part will be re-inserted into the new markdown file. If the new markdown has added parts the original responses will be placed correctly in the new file, but if any part is removed from the control in the update then any corresponding prose will be lost.
```

This is only true, I think, if the control has multiple parts to it. If not, then the file is re-generated and any previous edits are lost. And looking at the code, `existing_text` is only used when control parts are present, which seems to support my hypothesis. This [comment](https://github.com/IBM/compliance-trestle/blob/develop/trestle/core/control_io.py#L220-L223) in the relevant bit of the code seems to suggest that this once worked with top level elements. 

## To Reproduce

1. Create a new profile

```json
{
  "profile": {
    "uuid": "b7ac2bb6-75ec-411e-a162-378f50ac4ea3",
    "metadata": {
      "title": "Sample profile.",
      "last-modified": "2021-11-17T15:46:14.402466-08:00",
      "version": "0.0.0",
      "oscal-version": "1.0.0"
    },
    "imports": [
      {
        "href": "https://github.com/usnistgov/oscal-content/raw/master/nist.gov/SP800-53/rev5/json/NIST_SP-800-53_rev5_MODERATE-baseline-resolved-profile_catalog.json",
        "include-controls": [
          {
            "with-ids": [
              "ac-12"
            ]
          }
        ]
      }
    ]
  }
}
```

2. Run `trestle author ssp-generate -p test -o dist/system-security-plans/test` and observe that `ac-12.md` is generated.

3. Edit `ac-12.md`. 

```
sed -i "s/Add control/Something else/" dist/system-security-plans/test/ac-12.md
```

4. Re-run `trestle author ssp-generate -p test -o dist/system-security-plans/test`. The changes introduced above will be discarded. 

## Expected behavior

I would not want my control content to be overwritten when re-generating a ssp from a profile. Alternatively (the less better option) the documentation could be updated. 

## Screenshots / Logs.

Sample run

```
$ git diff | cat
diff --git a/dist/system-security-plans/test/ac-12.md b/dist/system-security-plans/test/ac-12.md
index 2aba1ba5..dbc5439f 100644
--- a/dist/system-security-plans/test/ac-12.md
+++ b/dist/system-security-plans/test/ac-12.md
@@ -22,6 +22,6 @@ ______________________________________________________________________

 ## What is the solution and how is it implemented?

-Add control implementation description here for control ac-12
+The solution is as follows...

 ______________________________________________________________________
$ trestle author ssp-generate -p test -o dist/system-security-plans/test
$ git diff | cat
<empty line>
```

## Environment

- OS: OSX Catalina 10.15.7
- Python version: 3.9.6
- Installed packages: compliance-trestle v0.30.0

**Comment by fsuits** [comment]
@cantsin Many thanks for reporting this.  I should have a fix shortly as part of an additional ssp enhancement PR.
