### ISSUE TITLE
The osco-to-oscal transformer should better insure OSCO scan results are supported

### ISSUE THREAD

**Issue by degenaro** [IBM/compliance-trestle#945]
## Issue description / feature objectives

The osco-to-oscal transformer expects to find either `host_name` in target-facts or `target`. Presently, no complaint is made if neither are found.

The modified behavior should be that if neither is found then an exception `openScap_version not supported: scan data format not recognized` should be thrown.

**Comment by vikas-agarwal76** [comment]
done
