### ISSUE TITLE
Support for inventory systems when `generating` an assessment plan?

### ISSUE THREAD

**Issue by butler54** [IBM/compliance-trestle#96]
## Issue description / feature objectives
As a user of OSCAL I would like to be able to keep my assessment-plan up to date with the lastest inventory from an external inventory system.

This information could come in as part of a 'fully' automated assessment-plan generation or a partial update process (e.g. just the inventory).

Inventory could be provided from a configuration management system such as ansible tower, a ERP platform, or via an abstraction such as auditree. Or even just a local document in the file system.

In order to inject the information into the system trestle will need one of the following:
1) A standardized inventory format? which can be used by other to refer to the system (maybe just a fractional oscal format)

2) Inventory provider layer to allow the information to be pulled in dynamically - part of core trestle.

3) Inventory provider layer that allows plugins

4) Functions on the above that allow a developer-user to create a custom workflow with trestle that supports this.

**Comment by butler54** [comment]
@drsm79 I think this is a question on the boundaries of trestle and auditree. Let's figure out what we want to do here.

**Comment by butler54** [comment]
Talking with @wanitasherchan if we were to have generic functions to bring inventory in *SOME* configuration must be required (even with auditree.

One way would be to have a simple intermediate format e.g:
```
{
    "inventory": [
        {
            "group_name":"",

            "items" : [{
                "key": "value"
            }]
        }
    ]
}
```
The other way is to have a simple mapping function like below.

spreadsheet with columns

A , B ,C , D, E, F

A function that converts it into inventory items
def inventory_spreadsheet(group_by=['A', 'B'], item_properties=["D","E","F"])

**Comment by drsm79** [comment]
I would:

- have an inventory data format that's close to, or easily compiles into, the OSCAL spec - can probably avoid things like addresses of data centres
- have tools (e.g. a harvest report) that generate that from evidence/source of truth

**Comment by butler54** [comment]
Closing expecting to open better scoped issues moving forward.
