### ISSUE TITLE
Log cleanup

### ISSUE THREAD

**Issue by vikas-agarwal76** [IBM/compliance-trestle#979]
Make logs 'look' friendlier - optional but not hard
Revisit log levels. - highly encouraged

**Comment by fsuits** [comment]
A way to do this is to create a new log level, perhaps TRACE, that is a level beyond DEBUG so that a verbose level of 2 or more will cause those lines to output also.  We can be doing this along with our current issues that are on a per-file basis so we can divide the work.

**Comment by vikas-agarwal76** [comment]
Mostly done. Also this is an ongoing activity.
