### ISSUE TITLE
Profile authoring tutorial references non-existant command line argument

### ISSUE THREAD

**Issue by deenine** [IBM/compliance-trestle#992]
## Describe the bug

[Profile authoring tutorial ](https://ibm.github.io/compliance-trestle/tutorials/ssp_profile_catalog_authoring/ssp_profile_catalog_authoring/)references non-existant command line argument `--profile_md`:

>In a cyclic operation of generate-edit-assemble you would simply be re-writing from and to the same json profile, in which case the --name is optional and you can just use `trestle author profile-assemble --profile_md --output my_profile`. This will assemble the markdown profile contents in directory profile_md into a json profile named my_profile but it will first use the existing my_profile json file as the parent profile and incorporate changes (due to user edits) in the markdown version of the profile.

```
(venv.trestle) Dougs-MacBook-Pro:~/workspace/control-profiles $trestle author profile-assemble --profile_md --output FSCloud_internal --markdown md_profiles
usage: trestle author profile-assemble [-h] [--name NAME] -m MARKDOWN --output OUTPUT [-sp] [-v] [--trestle-root TRESTLE_ROOT]
trestle author profile-assemble: error: unrecognized arguments: --profile_md
```

## To Reproduce

1. Click on '....'
1. Scroll down to '....'
1. See error

## Environment

- OS: \[e.g. iOS\]
- Python version:
- Installed packages:

**Comment by fsuits** [comment]
Thanks - instead of `--profile_md --output my_profile` it should say `--markdown profile_md --output my_profile`
Will fix
