### ISSUE TITLE
Errors reported as warnings

### ISSUE THREAD

**Issue by deenine** [IBM/compliance-trestle#995]
## Describe the bug

There are a number of cases where errors are reported by trestle as warnings, [for example](https://github.com/IBM/compliance-trestle/blob/79b2f61baac7adbf69e1474a5e218d664bec65ff/trestle/core/commands/author/profile.py#L125):

```
        except TrestleNotFoundError as e:
            logger.warning(f'Profile {profile_path} not found, error {e}')
            return CmdReturnCodes.COMMAND_ERROR.value
        except TrestleError as e:
            logger.warning(f'Error generating the catalog as markdown: {e}')
            return CmdReturnCodes.COMMAND_ERROR.value`
```

resulting in 'warnings' like:
```$trestle author profile-generate  --output md_profiles/FSCloud_internal --name FSCloud_internal
trestle.core.commands.author.profile:129 WARNING: Error generating the catalog as markdown: Set parameter object in profile does not have a corresponding param-id: "ac-1_prm_1"```


## Expected behavior

Fatal errors should be raised as logger.error, not logger.warning. 

Suggest this should be reviewed across the project.

**Comment by deenine** [comment]
Talked with @fsuits, the intent is that Error should indicate an internal processing error and Warning should indicate the user supplied bad data. I kinda agree with this concept, but we should document it somewhere, and we should also make it clear to the user if their bad data has prevented the task from completing

**Comment by vikas-agarwal76** [comment]
done
