### ISSUE TITLE
Enhanced catalog/profile/guidance management

### ISSUE THREAD

**Issue by deenine** [IBM/compliance-trestle#996]
## Issue description / feature objectives

**Objective** - allow an organisation to devolve ownership for the catalog, profile, guidance and SSP to different individuals or groups

This would be done via separate repositories for catalog, profile, guidance, and SSP (or other implementation documentation), storing the content at each level as markdown and using trestle to transform that into markdown into OSCAL json, to pass to the next level in the chain as a pull request to update the content. 

The flow of content is as follows:
<img width="519" alt="Screenshot 2022-01-20 at 12 43 13" src="https://user-images.githubusercontent.com/10449520/150340944-171a5cbf-a949-4625-931c-b9beef289cf6.png">

All controls in the catalog flow to the profile as oscal, where a subset of controls is selected and parameters are assigned, to create a profile. The profile then flows to consumers as Oscar, such as guidance and documentation. When guidance (how to meet a control) is updated, the prose is sent to the documentation (how a control is met) as an issue that the guidance for control or group of controls has been updated, and therefore the documentation for those controls must be reviewed to ensure validity.

_For example, a catalog owner updates a control in the catalog:_
1. catalog owner edits markdown of catalog, creates pull request to catalog with proposed changes.
2. catalog approver reviews and approves the changes to the catalog
3. trestle CI detects merged changes to markdown, updates OSCAL json catalog with changes to markdown and commits back to the catalog repo.
4. trestle CI creates a pull request(s) on configured consumers of the catalog (i.e. the profiles repo) requesting the owner of the profiles updates the catalog in the profiles repo.

I think the following functionality is required to enable this:
[ ] - Editable parameters defined in a control in the profile markdown for that control, which are populated into the json profile. For example a list of parameters in AC-1, e.g. ac-1_prm_1, ac-1_prm_2, ac-1_prm_3 in the yaml header for the control, set to the default for that parameter from the catalog, which the profile author can specify, and are then populated into the json profile when `profile-assemble` is run. 
[ ] - Validation that parameters in the profile match the catalog - for example if a control is modified to add an additional parameter, trestle profile validate should populate the profile markdown with the default values from the catalog, and print that new parameters are specified and should be populated by the profile author (which can then be turned into an issue on the profile by the CI/CD). The workflows for create new control in catalog and delete control in catalog will require determination. This is probably part of a wider problem about 'how can we use trestle to validate content and plug in to a CI/CD.
[ ] - The ability to separate guidance from being part of the profile into a separate repo.

**Comment by fsuits** [comment]
I have opened dependent issue #1004 to provide a mechanism that prevents people from exceeding their allowed scope of editing changes.
