### ISSUE TITLE
Please add me to write access

### ISSUE THREAD

**Issue by butler54** [IBM/compliance-trestle#998]
I would like collaborator (write) access to this repository.

- [x] I have read the [contributing guidelines][contributing]
- [x] I understand the responsibilities of a collaborator are to:
  - help review contributions to the compliance-trestle tool
  - help make & test releases
  - help promote the project

I believe that my access died transitioning organsations due to automated clean up. I've got some work I want to do on:
- https://github.com/IBM/compliance-trestle
- https://github.com/IBM/compliance-trestle-demos
- https://github.com/IBM/compliance-trestle-ssp-demo

[contributing]: https://github.com/IBM/compliance-trestle/blob/main/CONTRIBUTING.md

**Comment by vikas-agarwal76** [comment]
@butler54 Done.
